#!/bin/bash
echo "Removing all Bios, if are present"
echo
rm "system/5200.rom"
rm "system/7800 BIOS (U).rom"
rm "system/areplay.bin"
rm "system/ATARIBAS.ROM"
rm "system/ATARIOSA.ROM"
rm "system/ATARIOSB.ROM"
rm "system/ATARIXL.ROM"
rm "system/bios_CD_E.bin"
rm "system/bios_CD_J.bin"
rm "system/bios_CD_U.bin"
rm "system/bios_E.sms"
rm "system/bios.gg"
rm "system/bios_J.sms"
rm "system/bios_MD.bin"
rm "system/bios.min"
rm "system/bios_U.sms"
rm "system/BS-X.bin"
rm "system/c52.bin"
rm "system/disksys.rom"
rm "system/g7400.bin"
rm "system/gamegenie.nes"
rm "system/gba_bios.bin"
rm "system/gb_bios.bin"
rm "system/gbc_bios.bin"
rm "system/gexpress.pce"
rm "system/ggenie.bin"
rm "system/jopac.bin"
rm "system/lynxboot.img"
rm "system/o2rom.bin"
rm "system/pcfx.rom"
rm "system/PSXONPSP660.bin"
rm "system/scph1001.bin"
rm "system/scph101.bin"
rm "system/scph5500.bin"
rm "system/scph5501.bin"
rm "system/scph5502.bin"
rm "system/scph7001.bin"
rm "system/sgb_bios.bin"
rm "system/sk2chip.bin"
rm "system/sk.bin"
rm "system/STBIOS.bin"
rm "system/syscard1.pce"
rm "system/syscard2.pce"
rm "system/syscard3.pce"
rm "system/np2kai/2608_BD.WAV"
rm "system/np2kai/2608_HH.WAV"
rm "system/np2kai/2608_RIM.WAV"
rm "system/np2kai/2608_SD.WAV"
rm "system/np2kai/2608_TOM.WAV"
rm "system/np2kai/2608_TOP.WAV"
rm "system/np2kai/bios.rom"
rm "system/np2kai/bios9821.rom"
rm "system/np2kai/d8000.rom"
rm "system/np2kai/font.bmp"
rm "system/np2kai/FONT.ROM"
rm "system/np2kai/itf.rom"
rm "system/np2kai/sound.rom"
rm "system/Databases/colecodb.xml"
rm "system/Databases/msxcaswavdb.xml"
rm "system/Databases/msxromdb.xml"
rm "system/Databases/msxsysromdb.xml"
rm "system/Databases/segadb.xml"
rm "system/Databases/svidb.xml"
rm "system/Machines/COL - Bit Corporation Dina/config.ini"
rm "system/Machines/COL - Bit Corporation Dina/czz50-1.rom"
rm "system/Machines/COL - Bit Corporation Dina/czz50-2.rom"
rm "system/Machines/COL – ColecoVision/coleco.rom"
rm "system/Machines/COL – ColecoVision/config.ini"
rm "system/Machines/COL - ColecoVision with Opcode Memory Extension/coleco.rom"
rm "system/Machines/COL - ColecoVision with Opcode Memory Extension/config.ini"
rm "system/Machines/COL - Spectravideo SVI-603 Coleco/config.ini"
rm "system/Machines/COL - Spectravideo SVI-603 Coleco/SVI603.ROM"
rm "system/Machines/Forte II Games – Pesadelo/config.ini"
rm "system/Machines/Forte II Games – Pesadelo/pesadelo.rom"
rm "system/Machines/MSX/config.ini"
rm "system/Machines/MSX2/config.ini"
rm "system/Machines/MSX2+/config.ini"
rm "system/Machines/MSX2 - Al Alamiah AX-350/config.ini"
rm "system/Machines/MSX2 - Al Alamiah AX-370/config.ini"
rm "system/Machines/MSX2 – Arabic/config.ini"
rm "system/Machines/MSX2 – Brazilian/config.ini"
rm "system/Machines/MSX2+ - Brazilian/config.ini"
rm "system/Machines/MSX2 – C-BIOS/cbios_logo_msx2.rom"
rm "system/Machines/MSX2 – C-BIOS/cbios_main_msx2.rom"
rm "system/Machines/MSX2 – C-BIOS/cbios_sub.rom"
rm "system/Machines/MSX2 – C-BIOS/cbios.txt"
rm "system/Machines/MSX2 – C-BIOS/config.ini"
rm "system/Machines/MSX2+ - C-BIOS/cbios_logo_msx2+.rom"
rm "system/Machines/MSX2+ - C-BIOS/cbios_main_msx2+.rom"
rm "system/Machines/MSX2+ - C-BIOS/cbios_music.rom"
rm "system/Machines/MSX2+ - C-BIOS/cbios_sub.rom"
rm "system/Machines/MSX2+ - C-BIOS/cbios.txt"
rm "system/Machines/MSX2+ - C-BIOS/config.ini"
rm "system/Machines/MSX2+ - Ciel Expert 3 IDE/config.ini"
rm "system/Machines/MSX2+ - Ciel Expert 3 Turbo/config.ini"
rm "system/Machines/MSX2 - Daewoo CPC-300/config.ini"
rm "system/Machines/MSX2 - Daewoo CPC-300E/config.ini"
rm "system/Machines/MSX2 - Daewoo CPC-400/config.ini"
rm "system/Machines/MSX2 - Daewoo CPC-400S/config.ini"
rm "system/Machines/MSX2 – Estonian/config.ini"
rm "system/Machines/MSX2+ - European/config.ini"
rm "system/Machines/MSX2+ - European/KANJI.rom"
rm "system/Machines/MSX2+ - European/Msx2pe.rom"
rm "system/Machines/MSX2+ - European/Msx2pexte.rom"
rm "system/Machines/MSX2+ - European/MSX2PMUS.rom"
rm "system/Machines/MSX2+ - European/MSXKANJI.rom"
rm "system/Machines/MSX2+ - European/PANASONICDISK.rom"
rm "system/Machines/MSX2+ - European/XBASIC2.rom"
rm "system/Machines/MSX2 – French/config.ini"
rm "system/Machines/MSX2 – German/config.ini"
rm "system/Machines/MSX2 - Gradiente Expert 2.0/config.ini"
rm "system/Machines/MSX2+ - Gradiente Expert AC88+/config.ini"
rm "system/Machines/MSX2+ - Gradiente Expert DDX+/config.ini"
rm "system/Machines/MSX2 – Japanese/config.ini"
rm "system/Machines/MSX2 – Korean/config.ini"
rm "system/Machines/MSX2+ - MSXPLAYer 2003/config.ini"
rm "system/Machines/MSX2 - National FS-4500/config.ini"
rm "system/Machines/MSX2 - National FS-4600/config.ini"
rm "system/Machines/MSX2 - National FS-4700/config.ini"
rm "system/Machines/MSX2 - National FS-5000/config.ini"
rm "system/Machines/MSX2 - National FS-5500F1/config.ini"
rm "system/Machines/MSX2 - National FS-5500F2/config.ini"
rm "system/Machines/MSX2 - Only PSG/config.ini"
rm "system/Machines/MSX2 - Panasonic FS-A1/config.ini"
rm "system/Machines/MSX2 - Panasonic FS-A1 (a)/config.ini"
rm "system/Machines/MSX2 - Panasonic FS-A1F/config.ini"
rm "system/Machines/MSX2 - Panasonic FS-A1FM/config.ini"
rm "system/Machines/MSX2+ - Panasonic FS-A1FX/config.ini"
rm "system/Machines/MSX2 - Panasonic FS-A1MK2/config.ini"
rm "system/Machines/MSX2+ - Panasonic FS-A1WSX/config.ini"
rm "system/Machines/MSX2+ - Panasonic FS-A1WX/config.ini"
rm "system/Machines/MSX2+ - Panasonic FS-A1WX (a)/config.ini"
rm "system/Machines/MSX2 - Philips NMS-8220/config.ini"
rm "system/Machines/MSX2 - Philips NMS-8220 (a)/config.ini"
rm "system/Machines/MSX2 - Philips NMS-8245/config.ini"
rm "system/Machines/MSX2 - Philips NMS-8245F/config.ini"
rm "system/Machines/MSX2 - Philips NMS-8250/config.ini"
rm "system/Machines/MSX2 - Philips NMS-8255/config.ini"
rm "system/Machines/MSX2 - Philips NMS-8280/config.ini"
rm "system/Machines/MSX2 - Philips NMS-8280G/config.ini"
rm "system/Machines/MSX2 - Philips VG-8230/config.ini"
rm "system/Machines/MSX2 - Philips VG-8235/config.ini"
rm "system/Machines/MSX2 - Philips VG-8235F/config.ini"
rm "system/Machines/MSX2 - Philips VG-8240/config.ini"
rm "system/Machines/MSX2 – Russian/config.ini"
rm "system/Machines/MSX2 - Sanyo Wavy MPC-25FD/config.ini"
rm "system/Machines/MSX2 - Sanyo Wavy PHC-23/config.ini"
rm "system/Machines/MSX2+ - Sanyo Wavy PHC-35J/config.ini"
rm "system/Machines/MSX2+ - Sanyo Wavy PHC-70FD1/config.ini"
rm "system/Machines/MSX2+ - Sanyo Wavy PHC-70FD2/config.ini"
rm "system/Machines/MSX2 - Sharp Epcom HotBit 2.0/config.ini"
rm "system/Machines/MSX2 - Sony HB-F1/config.ini"
rm "system/Machines/MSX2 - Sony HB-F1II/config.ini"
rm "system/Machines/MSX2 - Sony HB-F1XD/config.ini"
rm "system/Machines/MSX2+ - Sony HB-F1XDJ/config.ini"
rm "system/Machines/MSX2 - Sony HB-F1XDMK2/config.ini"
rm "system/Machines/MSX2+ - Sony HB-F1XV/config.ini"
rm "system/Machines/MSX2 - Sony HB-F500/config.ini"
rm "system/Machines/MSX2 - Sony HB-F500P/config.ini"
rm "system/Machines/MSX2 - Sony HB-F700D/config.ini"
rm "system/Machines/MSX2 - Sony HB-F700F/config.ini"
rm "system/Machines/MSX2 - Sony HB-F700P/config.ini"
rm "system/Machines/MSX2 - Sony HB-F700S/config.ini"
rm "system/Machines/MSX2 - Sony HB-F900/config.ini"
rm "system/Machines/MSX2 - Sony HB-F900 (a)/config.ini"
rm "system/Machines/MSX2 - Sony HB-F9P/config.ini"
rm "system/Machines/MSX2 - Sony HB-F9P Russian/config.ini"
rm "system/Machines/MSX2 - Sony HB-F9S/config.ini"
rm "system/Machines/MSX2+ - Sony HB-F9S+/config.ini"
rm "system/Machines/MSX2 - Sony HB-G900AP/config.ini"
rm "system/Machines/MSX2 - Sony HB-G900P/config.ini"
rm "system/Machines/MSX2 – Spanish/config.ini"
rm "system/Machines/MSX2 - Spectravideo SVI-738-2 CUC/config.ini"
rm "system/Machines/MSX2 - Spectravideo SVI-738-2 JP Grobler/config.ini"
rm "system/Machines/MSX2 - Spectravideo SVI-738-2 LC Grosso/config.ini"
rm "system/Machines/MSX2 – Swedish/config.ini"
rm "system/Machines/MSX2 - Talent TPC-310/config.ini"
rm "system/Machines/MSX2 - Toshiba HX-23/config.ini"
rm "system/Machines/MSX2 - Toshiba HX-23F/config.ini"
rm "system/Machines/MSX2 - Virtual Haesung Console/config.ini"
rm "system/Machines/MSX2 - Yamaha CX7M/config.ini"
rm "system/Machines/MSX2 - Yamaha CX7M-128/config.ini"
rm "system/Machines/MSX - Al Alamiah AX-170/config.ini"
rm "system/Machines/MSX – Arabic/config.ini"
rm "system/Machines/MSX – Brazilian/config.ini"
rm "system/Machines/MSX - Canon V-10/config.ini"
rm "system/Machines/MSX - Canon V-20/config.ini"
rm "system/Machines/MSX – C-BIOS/cbios_logo_msx1.rom"
rm "system/Machines/MSX – C-BIOS/cbios_main_msx1.rom"
rm "system/Machines/MSX – C-BIOS/cbios.txt"
rm "system/Machines/MSX – C-BIOS/config.ini"
rm "system/Machines/MSX - Daewoo DPC-100/config.ini"
rm "system/Machines/MSX - Daewoo DPC-180/config.ini"
rm "system/Machines/MSX - Daewoo DPC-200/config.ini"
rm "system/Machines/MSX - Daewoo DPC-200E/config.ini"
rm "system/Machines/MSX – Estonian/config.ini"
rm "system/Machines/MSX - Frael Bruc 100-1/config.ini"
rm "system/Machines/MSX – French/config.ini"
rm "system/Machines/MSX – German/config.ini"
rm "system/Machines/MSX - Goldstar FC-200/config.ini"
rm "system/Machines/MSX - Gradiente Expert 1.0/config.ini"
rm "system/Machines/MSX - Gradiente Expert 1.1/config.ini"
rm "system/Machines/MSX - Gradiente Expert 1.3/config.ini"
rm "system/Machines/MSX - Gradiente Expert DDPlus/config.ini"
rm "system/Machines/MSX - Gradiente Expert Plus/config.ini"
rm "system/Machines/MSX – Japanese/config.ini"
rm "system/Machines/MSX - JVC HC-7GB/config.ini"
rm "system/Machines/MSX – Korean/config.ini"
rm "system/Machines/MSX - Mitsubishi ML-F80/config.ini"
rm "system/Machines/MSX - Mitsubishi ML-FX1/config.ini"
rm "system/Machines/MSX - National CF-1200/config.ini"
rm "system/Machines/MSX - National CF-2000/config.ini"
rm "system/Machines/MSX - National CF-2700/config.ini"
rm "system/Machines/MSX - National CF-3000/config.ini"
rm "system/Machines/MSX - National CF-3300/config.ini"
rm "system/Machines/MSX - National FS-1300/config.ini"
rm "system/Machines/MSX - National FS-4000/config.ini"
rm "system/Machines/MSX - Olympia PHC-2/config.ini"
rm "system/Machines/MSX - Olympia PHC-28/config.ini"
rm "system/Machines/MSX - Panasonic CF-2700G/config.ini"
rm "system/Machines/MSX - Philips NMS-801/config.ini"
rm "system/Machines/MSX - Philips VG-8000/config.ini"
rm "system/Machines/MSX - Philips VG-8010/config.ini"
rm "system/Machines/MSX - Philips VG-8010F/config.ini"
rm "system/Machines/MSX - Philips VG-8020-00/config.ini"
rm "system/Machines/MSX - Philips VG-8020-20/config.ini"
rm "system/Machines/MSX - Philips VG-8020F/config.ini"
rm "system/Machines/MSX - Pioneer PX-7/config.ini"
rm "system/Machines/MSX - Pioneer PX-V60/config.ini"
rm "system/Machines/MSX – Russian/config.ini"
rm "system/Machines/MSX - Sanyo MPC-100/config.ini"
rm "system/Machines/MSX - Sanyo MPC-64/config.ini"
rm "system/Machines/MSX - Sanyo PHC-28L/config.ini"
rm "system/Machines/MSX - Sanyo PHC-28S/config.ini"
rm "system/Machines/MSX - Sanyo Wavy MPC-10/config.ini"
rm "system/Machines/MSX - Sharp Epcom HotBit 1.1/config.ini"
rm "system/Machines/MSX - Sharp Epcom HotBit 1.2/config.ini"
rm "system/Machines/MSX - Sharp Epcom HotBit 1.3b/config.ini"
rm "system/Machines/MSX - Sharp Epcom HotBit 1.3p/config.ini"
rm "system/Machines/MSX - Sony HB-10P/config.ini"
rm "system/Machines/MSX - Sony HB-201/config.ini"
rm "system/Machines/MSX - Sony HB-201P/config.ini"
rm "system/Machines/MSX - Sony HB-20P/config.ini"
rm "system/Machines/MSX - Sony HB-501P/config.ini"
rm "system/Machines/MSX - Sony HB-55D/config.ini"
rm "system/Machines/MSX - Sony HB-55P/config.ini"
rm "system/Machines/MSX - Sony HB-75D/config.ini"
rm "system/Machines/MSX - Sony HB-75P/config.ini"
rm "system/Machines/MSX – Spanish/config.ini"
rm "system/Machines/MSX - Spectravideo SVI-728/config.ini"
rm "system/Machines/MSX - Spectravideo SVI-738/config.ini"
rm "system/Machines/MSX - Spectravideo SVI-738 Henrik Gilvad/config.ini"
rm "system/Machines/MSX - Spectravideo SVI-738 Swedish/config.ini"
rm "system/Machines/MSX – Swedish/config.ini"
rm "system/Machines/MSX - Talent DPC-200/config.ini"
rm "system/Machines/MSX - Talent DPC-200A/config.ini"
rm "system/Machines/MSX - Toshiba HX-10/config.ini"
rm "system/Machines/MSX - Toshiba HX-10S/config.ini"
rm "system/Machines/MSX - Toshiba HX-20/config.ini"
rm "system/Machines/MSXturboR/config.ini"
rm "system/Machines/MSXturboR – European/config.ini"
rm "system/Machines/MSXturboR - Panasonic FS-A1GT/config.ini"
rm "system/Machines/MSXturboR - Panasonic FS-A1ST/config.ini"
rm "system/Machines/MSXturboR - Panasonic FS-A1ST (a)/config.ini"
rm "system/Machines/MSXturboR - Panasonic FS-A1ST (b)/config.ini"
rm "system/Machines/MSX - Yamaha CX5M-1/config.ini"
rm "system/Machines/MSX - Yamaha CX5M-128/config.ini"
rm "system/Machines/MSX - Yamaha CX5M-2/config.ini"
rm "system/Machines/MSX - Yamaha CX5MII/config.ini"
rm "system/Machines/MSX - Yamaha YIS303/config.ini"
rm "system/Machines/MSX - Yamaha YIS503/config.ini"
rm "system/Machines/MSX - Yamaha YIS503F/config.ini"
rm "system/Machines/MSX - Yamaha YIS503II/config.ini"
rm "system/Machines/MSX - Yamaha YIS503IIR/config.ini"
rm "system/Machines/MSX - Yamaha YIS503IIR Estonian/config.ini"
rm "system/Machines/MSX - Yamaha YIS503M/config.ini"
rm "system/Machines/MSX - Yashica YC-64/config.ini"
rm "system/Machines/MSX - Yeno DPC-64/config.ini"
rm "system/Machines/MSX - Yeno MX64/config.ini"
rm "system/Machines/SEGA – SC-3000/config.ini"
rm "system/Machines/SEGA – SF-7000/config.ini"
rm "system/Machines/SEGA – SF-7000/sf7000.rom"
rm "system/Machines/SEGA – SG-1000/config.ini"
rm "system/Machines/Shared Roms/ARAB1.ROM"
rm "system/Machines/Shared Roms/ARABIC.rom"
rm "system/Machines/Shared Roms/BEERIDE.ROM"
rm "system/Machines/Shared Roms/FMPAC.rom"
rm "system/Machines/Shared Roms/GCVMX80.ROM"
rm "system/Machines/Shared Roms/HANGUL.rom"
rm "system/Machines/Shared Roms/KANJI.rom"
rm "system/Machines/Shared Roms/MICROSOLDISK.ROM"
rm "system/Machines/Shared Roms/MOONSOUND.rom"
rm "system/Machines/Shared Roms/MSX2AREXT.ROM"
rm "system/Machines/Shared Roms/MSX2AR.ROM"
rm "system/Machines/Shared Roms/MSX2BREXT.rom"
rm "system/Machines/Shared Roms/MSX2BR.rom"
rm "system/Machines/Shared Roms/MSX2EXT.rom"
rm "system/Machines/Shared Roms/MSX2FREXT.rom"
rm "system/Machines/Shared Roms/MSX2FR.rom"
rm "system/Machines/Shared Roms/MSX2GEXT.rom"
rm "system/Machines/Shared Roms/MSX2G.rom"
rm "system/Machines/Shared Roms/MSX2HAN.rom"
rm "system/Machines/Shared Roms/MSX2JEXT.rom"
rm "system/Machines/Shared Roms/MSX2J.rom"
rm "system/Machines/Shared Roms/MSX2KREXT.rom"
rm "system/Machines/Shared Roms/MSX2KR.rom"
rm "system/Machines/Shared Roms/MSX2PEXT.rom"
rm "system/Machines/Shared Roms/MSX2PMUS.rom"
rm "system/Machines/Shared Roms/MSX2P.rom"
rm "system/Machines/Shared Roms/MSX2R2.ROM"
rm "system/Machines/Shared Roms/MSX2REXT.rom"
rm "system/Machines/Shared Roms/MSX2.rom"
rm "system/Machines/Shared Roms/MSX2R.rom"
rm "system/Machines/Shared Roms/MSX2SE.rom"
rm "system/Machines/Shared Roms/MSX2SPEXT.rom"
rm "system/Machines/Shared Roms/MSX2SP.rom"
rm "system/Machines/Shared Roms/MSXAR.ROM"
rm "system/Machines/Shared Roms/MSXBR.rom"
rm "system/Machines/Shared Roms/MSXDOS23.ROM"
rm "system/Machines/Shared Roms/MSXFR.rom"
rm "system/Machines/Shared Roms/MSXG.rom"
rm "system/Machines/Shared Roms/MSXHAN.rom"
rm "system/Machines/Shared Roms/MSXJ.rom"
rm "system/Machines/Shared Roms/MSXKANJI.rom"
rm "system/Machines/Shared Roms/MSXKR.rom"
rm "system/Machines/Shared Roms/MSXR2.ROM"
rm "system/Machines/Shared Roms/MSX.rom"
rm "system/Machines/Shared Roms/MSXR.rom"
rm "system/Machines/Shared Roms/MSXSE.ROM"
rm "system/Machines/Shared Roms/MSXSP.rom"
rm "system/Machines/Shared Roms/MSXTREXT.ROM"
rm "system/Machines/Shared Roms/MSXTRMUS.ROM"
rm "system/Machines/Shared Roms/MSXTROPT.ROM"
rm "system/Machines/Shared Roms/MSXTR.ROM"
rm "system/Machines/Shared Roms/NATIONALDISK.rom"
rm "system/Machines/Shared Roms/NOVAXIS.rom"
rm "system/Machines/Shared Roms/nowindDos1.rom"
rm "system/Machines/Shared Roms/nowindDos2.rom"
rm "system/Machines/Shared Roms/PAINT.rom"
rm "system/Machines/Shared Roms/PANASONICDISK.rom"
rm "system/Machines/Shared Roms/PHILIPSDISK.rom"
rm "system/Machines/Shared Roms/RS232.ROM"
rm "system/Machines/Shared Roms/Shared.txt"
rm "system/Machines/Shared Roms/SUNRISEIDE.rom"
rm "system/Machines/Shared Roms/SWP.rom"
rm "system/Machines/Shared Roms/XBASIC2.rom"
rm "system/Machines/SVI - Spectravideo SVI-318/config.ini"
rm "system/Machines/SVI - Spectravideo SVI-318/svi318.rom"
rm "system/Machines/SVI - Spectravideo SVI-328/config.ini"
rm "system/Machines/SVI - Spectravideo SVI-328/svi328.rom"
rm "system/Machines/SVI - Spectravideo SVI-328 80 Column/config.ini"
rm "system/Machines/SVI - Spectravideo SVI-328 80 Column/svi328a.rom"
rm "system/Machines/SVI - Spectravideo SVI-328 80 Column/svi806.rom"
rm "system/Machines/SVI - Spectravideo SVI-328 80 Swedish/config.ini"
rm "system/Machines/SVI - Spectravideo SVI-328 80 Swedish/svi328a.rom"
rm "system/Machines/SVI - Spectravideo SVI-328 80 Swedish/svi806se.rom"
rm "system/Machines/SVI - Spectravideo SVI-328 MK2/config.ini"
rm "system/Machines/SVI - Spectravideo SVI-328 MK2/svi328a.rom"
rm "system/Machines/SVI - Spectravideo SVI-328 MK2/svi806.rom"
echo
echo "Making folders to put bios"
echo
mkdir "system/np2kai/"
mkdir "system/Databases/"
mkdit "system/Machines/"
mkdir "system/Machines/COL - Bit Corporation Dina/"
mkdir "system/Machines/COL – ColecoVision/"
mkdir "system/Machines/COL - ColecoVision with Opcode Memory Extension/"
mkdir "system/Machines/COL - Spectravideo SVI-603 Coleco/"
mkdir "system/Machines/Forte II Games – Pesadelo/"
mkdir "system/Machines/MSX/"
mkdir "system/Machines/MSX2/"
mkdir "system/Machines/MSX2+/"
mkdir "system/Machines/MSX2 - Al Alamiah AX-350/"
mkdir "system/Machines/MSX2 - Al Alamiah AX-370/"
mkdir "system/Machines/MSX2 – Arabic/"
mkdir "system/Machines/MSX2 – Brazilian/"
mkdir "system/Machines/MSX2+ - Brazilian/"
mkdir "system/Machines/MSX2 – C-BIOS/"
mkdir "system/Machines/MSX2+ - C-BIOS/"
mkdir "system/Machines/MSX2+ - Ciel Expert 3 IDE/"
mkdir "system/Machines/MSX2+ - Ciel Expert 3 Turbo/"
mkdir "system/Machines/MSX2 - Daewoo CPC-300/"
mkdir "system/Machines/MSX2 - Daewoo CPC-300E/"
mkdir "system/Machines/MSX2 - Daewoo CPC-400/"
mkdir "system/Machines/MSX2 - Daewoo CPC-400S/"
mkdir "system/Machines/MSX2 – Estonian/"
mkdir "system/Machines/MSX2+ - European/"
mkdir "system/Machines/MSX2 – French/"
mkdir "system/Machines/MSX2 – German/"
mkdir "system/Machines/MSX2 - Gradiente Expert 2.0/"
mkdir "system/Machines/MSX2+ - Gradiente Expert AC88+/"
mkdir "system/Machines/MSX2+ - Gradiente Expert DDX+/"
mkdir "system/Machines/MSX2 – Japanese/"
mkdir "system/Machines/MSX2 – Korean/"
mkdir "system/Machines/MSX2+ - MSXPLAYer 2003/"
mkdir "system/Machines/MSX2 - National FS-4500/"
mkdir "system/Machines/MSX2 - National FS-4600/"
mkdir "system/Machines/MSX2 - National FS-4700/"
mkdir "system/Machines/MSX2 - National FS-5000/"
mkdir "system/Machines/MSX2 - National FS-5500F1/"
mkdir "system/Machines/MSX2 - National FS-5500F2/"
mkdir "system/Machines/MSX2 - Only PSG/"
mkdir "system/Machines/MSX2 - Panasonic FS-A1/"
mkdir "system/Machines/MSX2 - Panasonic FS-A1 (a)/"
mkdir "system/Machines/MSX2 - Panasonic FS-A1F/"
mkdir "system/Machines/MSX2 - Panasonic FS-A1FM/"
mkdir "system/Machines/MSX2+ - Panasonic FS-A1FX/"
mkdir "system/Machines/MSX2 - Panasonic FS-A1MK2/"
mkdir "system/Machines/MSX2+ - Panasonic FS-A1WSX/"
mkdir "system/Machines/MSX2+ - Panasonic FS-A1WX/"
mkdir "system/Machines/MSX2+ - Panasonic FS-A1WX (a)/"
mkdir "system/Machines/MSX2 - Philips NMS-8220/"
mkdir "system/Machines/MSX2 - Philips NMS-8220 (a)/"
mkdir "system/Machines/MSX2 - Philips NMS-8245/"
mkdir "system/Machines/MSX2 - Philips NMS-8245F/"
mkdir "system/Machines/MSX2 - Philips NMS-8250/"
mkdir "system/Machines/MSX2 - Philips NMS-8255/"
mkdir "system/Machines/MSX2 - Philips NMS-8280/"
mkdir "system/Machines/MSX2 - Philips NMS-8280G/"
mkdir "system/Machines/MSX2 - Philips VG-8230/"
mkdir "system/Machines/MSX2 - Philips VG-8235/"
mkdir "system/Machines/MSX2 - Philips VG-8235F/"
mkdir "system/Machines/MSX2 - Philips VG-8240/"
mkdir "system/Machines/MSX2 – Russian/"
mkdir "system/Machines/MSX2 - Sanyo Wavy MPC-25FD/"
mkdir "system/Machines/MSX2 - Sanyo Wavy PHC-23/"
mkdir "system/Machines/MSX2+ - Sanyo Wavy PHC-35J/"
mkdir "system/Machines/MSX2+ - Sanyo Wavy PHC-70FD1/"
mkdir "system/Machines/MSX2+ - Sanyo Wavy PHC-70FD2/"
mkdir "system/Machines/MSX2 - Sharp Epcom HotBit 2.0/"
mkdir "system/Machines/MSX2 - Sony HB-F1/"
mkdir "system/Machines/MSX2 - Sony HB-F1II/"
mkdir "system/Machines/MSX2 - Sony HB-F1XD/"
mkdir "system/Machines/MSX2+ - Sony HB-F1XDJ/"
mkdir "system/Machines/MSX2 - Sony HB-F1XDMK2/"
mkdir "system/Machines/MSX2+ - Sony HB-F1XV/"
mkdir "system/Machines/MSX2 - Sony HB-F500/"
mkdir "system/Machines/MSX2 - Sony HB-F500P/"
mkdir "system/Machines/MSX2 - Sony HB-F700D/"
mkdir "system/Machines/MSX2 - Sony HB-F700F/"
mkdir "system/Machines/MSX2 - Sony HB-F700P/"
mkdir "system/Machines/MSX2 - Sony HB-F700S/"
mkdir "system/Machines/MSX2 - Sony HB-F900/"
mkdir "system/Machines/MSX2 - Sony HB-F900 (a)/"
mkdir "system/Machines/MSX2 - Sony HB-F9P/"
mkdir "system/Machines/MSX2 - Sony HB-F9P Russian/"
mkdir "system/Machines/MSX2 - Sony HB-F9S/"
mkdir "system/Machines/MSX2+ - Sony HB-F9S+/"
mkdir "system/Machines/MSX2 - Sony HB-G900AP/"
mkdir "system/Machines/MSX2 - Sony HB-G900P/"
mkdir "system/Machines/MSX2 – Spanish/"
mkdir "system/Machines/MSX2 - Spectravideo SVI-738-2 CUC/"
mkdir "system/Machines/MSX2 - Spectravideo SVI-738-2 JP Grobler/"
mkdir "system/Machines/MSX2 - Spectravideo SVI-738-2 LC Grosso/"
mkdir "system/Machines/MSX2 – Swedish/"
mkdir "system/Machines/MSX2 - Talent TPC-310/"
mkdir "system/Machines/MSX2 - Toshiba HX-23/"
mkdir "system/Machines/MSX2 - Toshiba HX-23F/"
mkdir "system/Machines/MSX2 - Virtual Haesung Console/"
mkdir "system/Machines/MSX2 - Yamaha CX7M/"
mkdir "system/Machines/MSX2 - Yamaha CX7M-128/"
mkdir "system/Machines/MSX - Al Alamiah AX-170/"
mkdir "system/Machines/MSX – Arabic/"
mkdir "system/Machines/MSX – Brazilian/"
mkdir "system/Machines/MSX - Canon V-10/"
mkdir "system/Machines/MSX - Canon V-20/"
mkdir "system/Machines/MSX – C-BIOS/"
mkdir "system/Machines/MSX - Daewoo DPC-100/"
mkdir "system/Machines/MSX - Daewoo DPC-180/"
mkdir "system/Machines/MSX - Daewoo DPC-200/"
mkdir "system/Machines/MSX - Daewoo DPC-200E/"
mkdir "system/Machines/MSX – Estonian/"
mkdir "system/Machines/MSX - Frael Bruc 100-1/"
mkdir "system/Machines/MSX – French/"
mkdir "system/Machines/MSX – German/"
mkdir "system/Machines/MSX - Goldstar FC-200/"
mkdir "system/Machines/MSX - Gradiente Expert 1.0/"
mkdir "system/Machines/MSX - Gradiente Expert 1.1/"
mkdir "system/Machines/MSX - Gradiente Expert 1.3/"
mkdir "system/Machines/MSX - Gradiente Expert DDPlus/"
mkdir "system/Machines/MSX - Gradiente Expert Plus/"
mkdir "system/Machines/MSX – Japanese/"
mkdir "system/Machines/MSX - JVC HC-7GB/"
mkdir "system/Machines/MSX – Korean/"
mkdir "system/Machines/MSX - Mitsubishi ML-F80/"
mkdir "system/Machines/MSX - Mitsubishi ML-FX1/"
mkdir "system/Machines/MSX - National CF-1200/"
mkdir "system/Machines/MSX - National CF-2000/"
mkdir "system/Machines/MSX - National CF-2700/"
mkdir "system/Machines/MSX - National CF-3000/"
mkdir "system/Machines/MSX - National CF-3300/"
mkdir "system/Machines/MSX - National FS-1300/"
mkdir "system/Machines/MSX - National FS-4000/"
mkdir "system/Machines/MSX - Olympia PHC-2/"
mkdir "system/Machines/MSX - Olympia PHC-28/"
mkdir "system/Machines/MSX - Panasonic CF-2700G/"
mkdir "system/Machines/MSX - Philips NMS-801/"
mkdir "system/Machines/MSX - Philips VG-8000/"
mkdir "system/Machines/MSX - Philips VG-8010/"
mkdir "system/Machines/MSX - Philips VG-8010F/"
mkdir "system/Machines/MSX - Philips VG-8020-00/"
mkdir "system/Machines/MSX - Philips VG-8020-20/"
mkdir "system/Machines/MSX - Philips VG-8020F/"
mkdir "system/Machines/MSX - Pioneer PX-7/"
mkdir "system/Machines/MSX - Pioneer PX-V60/"
mkdir "system/Machines/MSX – Russian/"
mkdir "system/Machines/MSX - Sanyo MPC-100/"
mkdir "system/Machines/MSX - Sanyo MPC-64/"
mkdir "system/Machines/MSX - Sanyo PHC-28L/"
mkdir "system/Machines/MSX - Sanyo PHC-28S/"
mkdir "system/Machines/MSX - Sanyo Wavy MPC-10/"
mkdir "system/Machines/MSX - Sharp Epcom HotBit 1.1/"
mkdir "system/Machines/MSX - Sharp Epcom HotBit 1.2/"
mkdir "system/Machines/MSX - Sharp Epcom HotBit 1.3b/"
mkdir "system/Machines/MSX - Sharp Epcom HotBit 1.3p/"
mkdir "system/Machines/MSX - Sony HB-10P/"
mkdir "system/Machines/MSX - Sony HB-201/"
mkdir "system/Machines/MSX - Sony HB-201P/"
mkdir "system/Machines/MSX - Sony HB-20P/"
mkdir "system/Machines/MSX - Sony HB-501P/"
mkdir "system/Machines/MSX - Sony HB-55D/"
mkdir "system/Machines/MSX - Sony HB-55P/"
mkdir "system/Machines/MSX - Sony HB-75D/"
mkdir "system/Machines/MSX - Sony HB-75P/"
mkdir "system/Machines/MSX – Spanish/"
mkdir "system/Machines/MSX - Spectravideo SVI-728/"
mkdir "system/Machines/MSX - Spectravideo SVI-738/"
mkdir "system/Machines/MSX - Spectravideo SVI-738 Henrik Gilvad/"
mkdir "system/Machines/MSX - Spectravideo SVI-738 Swedish/"
mkdir "system/Machines/MSX – Swedish/"
mkdir "system/Machines/MSX - Talent DPC-200/"
mkdir "system/Machines/MSX - Talent DPC-200A/"
mkdir "system/Machines/MSX - Toshiba HX-10/"
mkdir "system/Machines/MSX - Toshiba HX-10S/"
mkdir "system/Machines/MSX - Toshiba HX-20/"
mkdir "system/Machines/MSXturboR/"
mkdir "system/Machines/MSXturboR – European/"
mkdir "system/Machines/MSXturboR - Panasonic FS-A1GT/"
mkdir "system/Machines/MSXturboR - Panasonic FS-A1ST/"
mkdir "system/Machines/MSXturboR - Panasonic FS-A1ST (a)/"
mkdir "system/Machines/MSXturboR - Panasonic FS-A1ST (b)/"
mkdir "system/Machines/MSX - Yamaha CX5M-1/"
mkdir "system/Machines/MSX - Yamaha CX5M-128/"
mkdir "system/Machines/MSX - Yamaha CX5M-2/"
mkdir "system/Machines/MSX - Yamaha CX5MII/"
mkdir "system/Machines/MSX - Yamaha YIS303/"
mkdir "system/Machines/MSX - Yamaha YIS503/"
mkdir "system/Machines/MSX - Yamaha YIS503F/"
mkdir "system/Machines/MSX - Yamaha YIS503II/"
mkdir "system/Machines/MSX - Yamaha YIS503IIR/"
mkdir "system/Machines/MSX - Yamaha YIS503IIR Estonian/"
mkdir "system/Machines/MSX - Yamaha YIS503M/"
mkdir "system/Machines/MSX - Yashica YC-64/"
mkdir "system/Machines/MSX - Yeno DPC-64/"
mkdir "system/Machines/MSX - Yeno MX64/"
mkdir "system/Machines/SEGA – SC-3000/"
mkdir "system/Machines/SEGA – SF-7000/"
mkdir "system/Machines/SEGA – SG-1000/"
mkdir "system/Machines/Shared Roms/"
mkdir "system/Machines/SVI - Spectravideo SVI-318/"
mkdir "system/Machines/SVI - Spectravideo SVI-328/"
mkdir "system/Machines/SVI - Spectravideo SVI-328 80 Column/"
mkdir "system/Machines/SVI - Spectravideo SVI-328 80 Swedish/"
mkdir "system/Machines/SVI - Spectravideo SVI-328 MK2/"
echo
echo "Getting Bios"
echo
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/5200.rom" -P "system/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/7800 BIOS (U).rom" -P "system/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/areplay.bin" -P "system/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/ATARIBAS.ROM" -P "system/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/ATARIOSA.ROM" -P "system/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/ATARIOSB.ROM" -P "system/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/ATARIXL.ROM" -P "system/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/bios_CD_E.bin" -P "system/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/bios_CD_J.bin" -P "system/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/bios_CD_U.bin" -P "system/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/bios_E.sms" -P "system/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/bios.gg" -P "system/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/bios_J.sms" -P "system/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/bios_MD.bin" -P "system/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/bios.min" -P "system/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/bios_U.sms" -P "system/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/BS-X.bin" -P "system/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/c52.bin" -P "system/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/disksys.rom" -P "system/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/g7400.bin" -P "system/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/gamegenie.nes" -P "system/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/gba_bios.bin" -P "system/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/gb_bios.bin" -P "system/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/gbc_bios.bin" -P "system/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/gexpress.pce" -P "system/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/ggenie.bin" -P "system/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/jopac.bin" -P "system/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/lynxboot.img" -P "system/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/o2rom.bin" -P "system/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/pcfx.rom" -P "system/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/PSXONPSP660.bin" -P "system/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/scph1001.bin" -P "system/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/scph101.bin" -P "system/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/scph5500.bin" -P "system/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/scph5501.bin" -P "system/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/scph5502.bin" -P "system/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/scph7001.bin" -P "system/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/sgb_bios.bin" -P "system/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/sk2chip.bin" -P "system/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/sk.bin" -P "system/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/STBIOS.bin" -P "system/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/syscard1.pce" -P "system/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/syscard2.pce" -P "system/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/syscard3.pce" -P "system/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/np2kai/2608_BD.WAV" -P "system/np2kai/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/np2kai/2608_HH.WAV" -P "system/np2kai/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/np2kai/2608_RIM.WAV" -P "system/np2kai/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/np2kai/2608_SD.WAV" -P "system/np2kai/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/np2kai/2608_TOM.WAV" -P "system/np2kai/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/np2kai/2608_TOP.WAV" -P "system/np2kai/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/np2kai/bios.rom" -P "system/np2kai/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/np2kai/bios9821.rom" -P "system/np2kai/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/np2kai/d8000.rom" -P "system/np2kai/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/np2kai/font.bmp" -P "system/np2kai/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/np2kai/FONT.ROM" -P "system/np2kai/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/np2kai/itf.rom" -P "system/np2kai/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/np2kai/sound.rom" -P "system/np2kai/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/Databases/colecodb.xml" -P "system/Databases/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/Databases/msxcaswavdb.xml" -P "system/Databases/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/Databases/msxromdb.xml" -P "system/Databases/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/Databases/msxsysromdb.xml" -P "system/Databases/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/Databases/segadb.xml" -P "system/Databases/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/Databases/svidb.xml" -P "system/Databases/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/Machines/COL - Bit Corporation Dina/config.ini" -P "system/Machines/COL - Bit Corporation Dina/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/Machines/COL - Bit Corporation Dina/czz50-1.rom" -P "system/Machines/COL - Bit Corporation Dina/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/Machines/COL - Bit Corporation Dina/czz50-2.rom" -P "system/Machines/COL - Bit Corporation Dina/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/Machines/COL – ColecoVision/coleco.rom" -P "system/Machines/COL – ColecoVision/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/Machines/COL – ColecoVision/config.ini" -P "system/Machines/COL – ColecoVision/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/Machines/COL - ColecoVision with Opcode Memory Extension/coleco.rom" -P "system/Machines/COL - ColecoVision with Opcode Memory Extension/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/Machines/COL - ColecoVision with Opcode Memory Extension/config.ini" -P "system/Machines/COL - ColecoVision with Opcode Memory Extension/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/Machines/COL - Spectravideo SVI-603 Coleco/config.ini" -P "system/Machines/COL - Spectravideo SVI-603 Coleco/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/Machines/COL - Spectravideo SVI-603 Coleco/SVI603.ROM" -P "system/Machines/COL - Spectravideo SVI-603 Coleco/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/Machines/Forte II Games – Pesadelo/config.ini" -P "system/Machines/Forte II Games – Pesadelo/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/Machines/Forte II Games – Pesadelo/pesadelo.rom" -P "system/Machines/Forte II Games – Pesadelo/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/Machines/MSX/config.ini" -P "system/Machines/MSX/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/Machines/MSX2/config.ini" -P "system/Machines/MSX2/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/Machines/MSX2+/config.ini" -P "system/Machines/MSX2+/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/Machines/MSX2 - Al Alamiah AX-350/config.ini" -P "system/Machines/MSX2 - Al Alamiah AX-350/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/Machines/MSX2 - Al Alamiah AX-370/config.ini" -P "system/Machines/MSX2 - Al Alamiah AX-370/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/Machines/MSX2 – Arabic/config.ini" -P "system/Machines/MSX2 – Arabic/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/Machines/MSX2 – Brazilian/config.ini" -P "system/Machines/MSX2 – Brazilian/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/Machines/MSX2+ - Brazilian/config.ini" -P "system/Machines/MSX2+ - Brazilian/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/Machines/MSX2 – C-BIOS/cbios_logo_msx2.rom" -P "system/Machines/MSX2 – C-BIOS/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/Machines/MSX2 – C-BIOS/cbios_main_msx2.rom" -P "system/Machines/MSX2 – C-BIOS/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/Machines/MSX2 – C-BIOS/cbios_sub.rom" -P "system/Machines/MSX2 – C-BIOS/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/Machines/MSX2 – C-BIOS/cbios.txt" -P "system/Machines/MSX2 – C-BIOS/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/Machines/MSX2 – C-BIOS/config.ini" -P "system/Machines/MSX2 – C-BIOS/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/Machines/MSX2+ - C-BIOS/cbios_logo_msx2+.rom" -P "system/Machines/MSX2+ - C-BIOS/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/Machines/MSX2+ - C-BIOS/cbios_main_msx2+.rom" -P "system/Machines/MSX2+ - C-BIOS/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/Machines/MSX2+ - C-BIOS/cbios_music.rom" -P "system/Machines/MSX2+ - C-BIOS/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/Machines/MSX2+ - C-BIOS/cbios_sub.rom" -P "system/Machines/MSX2+ - C-BIOS/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/Machines/MSX2+ - C-BIOS/cbios.txt" -P "system/Machines/MSX2+ - C-BIOS/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/Machines/MSX2+ - C-BIOS/config.ini" -P "system/Machines/MSX2+ - C-BIOS/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/Machines/MSX2+ - Ciel Expert 3 IDE/config.ini" -P "system/Machines/MSX2+ - Ciel Expert 3 IDE/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/Machines/MSX2+ - Ciel Expert 3 Turbo/config.ini" -P "system/Machines/MSX2+ - Ciel Expert 3 Turbo/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/Machines/MSX2 - Daewoo CPC-300/config.ini" -P "system/Machines/MSX2 - Daewoo CPC-300/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/Machines/MSX2 - Daewoo CPC-300E/config.ini" -P "system/Machines/MSX2 - Daewoo CPC-300E/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/Machines/MSX2 - Daewoo CPC-400/config.ini" -P "system/Machines/MSX2 - Daewoo CPC-400/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/Machines/MSX2 - Daewoo CPC-400S/config.ini" -P "system/Machines/MSX2 - Daewoo CPC-400S/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/Machines/MSX2 – Estonian/config.ini" -P "system/Machines/MSX2 – Estonian/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/Machines/MSX2+ - European/config.ini" -P "system/Machines/MSX2+ - European/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/Machines/MSX2+ - European/KANJI.rom" -P "system/Machines/MSX2+ - European/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/Machines/MSX2+ - European/Msx2pe.rom" -P "system/Machines/MSX2+ - European/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/Machines/MSX2+ - European/Msx2pexte.rom" -P "system/Machines/MSX2+ - European/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/Machines/MSX2+ - European/MSX2PMUS.rom" -P "system/Machines/MSX2+ - European/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/Machines/MSX2+ - European/MSXKANJI.rom" -P "system/Machines/MSX2+ - European/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/Machines/MSX2+ - European/PANASONICDISK.rom" -P "system/Machines/MSX2+ - European/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/Machines/MSX2+ - European/XBASIC2.rom" -P "system/Machines/MSX2+ - European/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/Machines/MSX2 – French/config.ini" -P "system/Machines/MSX2 – French/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/Machines/MSX2 – German/config.ini" -P "system/Machines/MSX2 – German/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/Machines/MSX2 - Gradiente Expert 2.0/config.ini" -P "system/Machines/MSX2 - Gradiente Expert 2.0/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/Machines/MSX2+ - Gradiente Expert AC88+/config.ini" -P "system/Machines/MSX2+ - Gradiente Expert AC88+/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/Machines/MSX2+ - Gradiente Expert DDX+/config.ini" -P "system/Machines/MSX2+ - Gradiente Expert DDX+/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/Machines/MSX2 – Japanese/config.ini" -P "system/Machines/MSX2 – Japanese/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/Machines/MSX2 – Korean/config.ini" -P "system/Machines/MSX2 – Korean/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/Machines/MSX2+ - MSXPLAYer 2003/config.ini" -P "system/Machines/MSX2+ - MSXPLAYer 2003/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/Machines/MSX2 - National FS-4500/config.ini" -P "system/Machines/MSX2 - National FS-4500/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/Machines/MSX2 - National FS-4600/config.ini" -P "system/Machines/MSX2 - National FS-4600/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/Machines/MSX2 - National FS-4700/config.ini" -P "system/Machines/MSX2 - National FS-4700/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/Machines/MSX2 - National FS-5000/config.ini" -P "system/Machines/MSX2 - National FS-5000/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/Machines/MSX2 - National FS-5500F1/config.ini" -P "system/Machines/MSX2 - National FS-5500F1/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/Machines/MSX2 - National FS-5500F2/config.ini" -P "system/Machines/MSX2 - National FS-5500F2/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/Machines/MSX2 - Only PSG/config.ini" -P "system/Machines/MSX2 - Only PSG/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/Machines/MSX2 - Panasonic FS-A1/config.ini" -P "system/Machines/MSX2 - Panasonic FS-A1/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/Machines/MSX2 - Panasonic FS-A1 (a)/config.ini" -P "system/Machines/MSX2 - Panasonic FS-A1 (a)/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/Machines/MSX2 - Panasonic FS-A1F/config.ini" -P "system/Machines/MSX2 - Panasonic FS-A1F/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/Machines/MSX2 - Panasonic FS-A1FM/config.ini" -P "system/Machines/MSX2 - Panasonic FS-A1FM/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/Machines/MSX2+ - Panasonic FS-A1FX/config.ini" -P "system/Machines/MSX2+ - Panasonic FS-A1FX/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/Machines/MSX2 - Panasonic FS-A1MK2/config.ini" -P "system/Machines/MSX2 - Panasonic FS-A1MK2/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/Machines/MSX2+ - Panasonic FS-A1WSX/config.ini" -P "system/Machines/MSX2+ - Panasonic FS-A1WSX/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/Machines/MSX2+ - Panasonic FS-A1WX/config.ini" -P "system/Machines/MSX2+ - Panasonic FS-A1WX/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/Machines/MSX2+ - Panasonic FS-A1WX (a)/config.ini" -P "system/Machines/MSX2+ - Panasonic FS-A1WX (a)/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/Machines/MSX2 - Philips NMS-8220/config.ini" -P "system/Machines/MSX2 - Philips NMS-8220/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/Machines/MSX2 - Philips NMS-8220 (a)/config.ini" -P "system/Machines/MSX2 - Philips NMS-8220 (a)/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/Machines/MSX2 - Philips NMS-8245/config.ini" -P "system/Machines/MSX2 - Philips NMS-8245/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/Machines/MSX2 - Philips NMS-8245F/config.ini" -P "system/Machines/MSX2 - Philips NMS-8245F/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/Machines/MSX2 - Philips NMS-8250/config.ini" -P "system/Machines/MSX2 - Philips NMS-8250/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/Machines/MSX2 - Philips NMS-8255/config.ini" -P "system/Machines/MSX2 - Philips NMS-8255/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/Machines/MSX2 - Philips NMS-8280/config.ini" -P "system/Machines/MSX2 - Philips NMS-8280/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/Machines/MSX2 - Philips NMS-8280G/config.ini" -P "system/Machines/MSX2 - Philips NMS-8280G/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/Machines/MSX2 - Philips VG-8230/config.ini" -P "system/Machines/MSX2 - Philips VG-8230/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/Machines/MSX2 - Philips VG-8235/config.ini" -P "system/Machines/MSX2 - Philips VG-8235/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/Machines/MSX2 - Philips VG-8235F/config.ini" -P "system/Machines/MSX2 - Philips VG-8235F/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/Machines/MSX2 - Philips VG-8240/config.ini" -P "system/Machines/MSX2 - Philips VG-8240/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/Machines/MSX2 – Russian/config.ini" -P "system/Machines/MSX2 – Russian/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/Machines/MSX2 - Sanyo Wavy MPC-25FD/config.ini" -P "system/Machines/MSX2 - Sanyo Wavy MPC-25FD/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/Machines/MSX2 - Sanyo Wavy PHC-23/config.ini" -P "system/Machines/MSX2 - Sanyo Wavy PHC-23/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/Machines/MSX2+ - Sanyo Wavy PHC-35J/config.ini" -P "system/Machines/MSX2+ - Sanyo Wavy PHC-35J/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/Machines/MSX2+ - Sanyo Wavy PHC-70FD1/config.ini" -P "system/Machines/MSX2+ - Sanyo Wavy PHC-70FD1/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/Machines/MSX2+ - Sanyo Wavy PHC-70FD2/config.ini" -P "system/Machines/MSX2+ - Sanyo Wavy PHC-70FD2/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/Machines/MSX2 - Sharp Epcom HotBit 2.0/config.ini" -P "system/Machines/MSX2 - Sharp Epcom HotBit 2.0/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/Machines/MSX2 - Sony HB-F1/config.ini" -P "system/Machines/MSX2 - Sony HB-F1/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/Machines/MSX2 - Sony HB-F1II/config.ini" -P "system/Machines/MSX2 - Sony HB-F1II/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/Machines/MSX2 - Sony HB-F1XD/config.ini" -P "system/Machines/MSX2 - Sony HB-F1XD/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/Machines/MSX2+ - Sony HB-F1XDJ/config.ini" -P "system/Machines/MSX2+ - Sony HB-F1XDJ/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/Machines/MSX2 - Sony HB-F1XDMK2/config.ini" -P "system/Machines/MSX2 - Sony HB-F1XDMK2/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/Machines/MSX2+ - Sony HB-F1XV/config.ini" -P "system/Machines/MSX2+ - Sony HB-F1XV/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/Machines/MSX2 - Sony HB-F500/config.ini" -P "system/Machines/MSX2 - Sony HB-F500/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/Machines/MSX2 - Sony HB-F500P/config.ini" -P "system/Machines/MSX2 - Sony HB-F500P/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/Machines/MSX2 - Sony HB-F700D/config.ini" -P "system/Machines/MSX2 - Sony HB-F700D/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/Machines/MSX2 - Sony HB-F700F/config.ini" -P "system/Machines/MSX2 - Sony HB-F700F/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/Machines/MSX2 - Sony HB-F700P/config.ini" -P "system/Machines/MSX2 - Sony HB-F700P/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/Machines/MSX2 - Sony HB-F700S/config.ini" -P "system/Machines/MSX2 - Sony HB-F700S/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/Machines/MSX2 - Sony HB-F900/config.ini" -P "system/Machines/MSX2 - Sony HB-F900/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/Machines/MSX2 - Sony HB-F900 (a)/config.ini" -P "system/Machines/MSX2 - Sony HB-F900 (a)/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/Machines/MSX2 - Sony HB-F9P/config.ini" -P "system/Machines/MSX2 - Sony HB-F9P/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/Machines/MSX2 - Sony HB-F9P Russian/config.ini" -P "system/Machines/MSX2 - Sony HB-F9P Russian/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/Machines/MSX2 - Sony HB-F9S/config.ini" -P "system/Machines/MSX2 - Sony HB-F9S/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/Machines/MSX2+ - Sony HB-F9S+/config.ini" -P "system/Machines/MSX2+ - Sony HB-F9S+/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/Machines/MSX2 - Sony HB-G900AP/config.ini" -P "system/Machines/MSX2 - Sony HB-G900AP/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/Machines/MSX2 - Sony HB-G900P/config.ini" -P "system/Machines/MSX2 - Sony HB-G900P/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/Machines/MSX2 – Spanish/config.ini" -P "system/Machines/MSX2 – Spanish/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/Machines/MSX2 - Spectravideo SVI-738-2 CUC/config.ini" -P "system/Machines/MSX2 - Spectravideo SVI-738-2 CUC/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/Machines/MSX2 - Spectravideo SVI-738-2 JP Grobler/config.ini" -P "system/Machines/MSX2 - Spectravideo SVI-738-2 JP Grobler/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/Machines/MSX2 - Spectravideo SVI-738-2 LC Grosso/config.ini" -P "system/Machines/MSX2 - Spectravideo SVI-738-2 LC Grosso/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/Machines/MSX2 – Swedish/config.ini" -P "system/Machines/MSX2 – Swedish/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/Machines/MSX2 - Talent TPC-310/config.ini" -P "system/Machines/MSX2 - Talent TPC-310/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/Machines/MSX2 - Toshiba HX-23/config.ini" -P "system/Machines/MSX2 - Toshiba HX-23/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/Machines/MSX2 - Toshiba HX-23F/config.ini" -P "system/Machines/MSX2 - Toshiba HX-23F/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/Machines/MSX2 - Virtual Haesung Console/config.ini" -P "system/Machines/MSX2 - Virtual Haesung Console/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/Machines/MSX2 - Yamaha CX7M/config.ini" -P "system/Machines/MSX2 - Yamaha CX7M/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/Machines/MSX2 - Yamaha CX7M-128/config.ini" -P "system/Machines/MSX2 - Yamaha CX7M-128/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/Machines/MSX - Al Alamiah AX-170/config.ini" -P "system/Machines/MSX - Al Alamiah AX-170/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/Machines/MSX – Arabic/config.ini" -P "system/Machines/MSX – Arabic/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/Machines/MSX – Brazilian/config.ini" -P "system/Machines/MSX – Brazilian/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/Machines/MSX - Canon V-10/config.ini" -P "system/Machines/MSX - Canon V-10/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/Machines/MSX - Canon V-20/config.ini" -P "system/Machines/MSX - Canon V-20/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/Machines/MSX – C-BIOS/cbios_logo_msx1.rom" -P "system/Machines/MSX – C-BIOS/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/Machines/MSX – C-BIOS/cbios_main_msx1.rom" -P "system/Machines/MSX – C-BIOS/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/Machines/MSX – C-BIOS/cbios.txt" -P "system/Machines/MSX – C-BIOS/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/Machines/MSX – C-BIOS/config.ini" -P "system/Machines/MSX – C-BIOS/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/Machines/MSX - Daewoo DPC-100/config.ini" -P "system/Machines/MSX - Daewoo DPC-100/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/Machines/MSX - Daewoo DPC-180/config.ini" -P "system/Machines/MSX - Daewoo DPC-180/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/Machines/MSX - Daewoo DPC-200/config.ini" -P "system/Machines/MSX - Daewoo DPC-200/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/Machines/MSX - Daewoo DPC-200E/config.ini" -P "system/Machines/MSX - Daewoo DPC-200E/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/Machines/MSX – Estonian/config.ini" -P "system/Machines/MSX – Estonian/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/Machines/MSX - Frael Bruc 100-1/config.ini" -P "system/Machines/MSX - Frael Bruc 100-1/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/Machines/MSX – French/config.ini" -P "system/Machines/MSX – French/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/Machines/MSX – German/config.ini" -P "system/Machines/MSX – German/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/Machines/MSX - Goldstar FC-200/config.ini" -P "system/Machines/MSX - Goldstar FC-200/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/Machines/MSX - Gradiente Expert 1.0/config.ini" -P "system/Machines/MSX - Gradiente Expert 1.0/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/Machines/MSX - Gradiente Expert 1.1/config.ini" -P "system/Machines/MSX - Gradiente Expert 1.1/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/Machines/MSX - Gradiente Expert 1.3/config.ini" -P "system/Machines/MSX - Gradiente Expert 1.3/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/Machines/MSX - Gradiente Expert DDPlus/config.ini" -P "system/Machines/MSX - Gradiente Expert DDPlus/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/Machines/MSX - Gradiente Expert Plus/config.ini" -P "system/Machines/MSX - Gradiente Expert Plus/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/Machines/MSX – Japanese/config.ini" -P "system/Machines/MSX – Japanese/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/Machines/MSX - JVC HC-7GB/config.ini" -P "system/Machines/MSX - JVC HC-7GB/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/Machines/MSX – Korean/config.ini" -P "system/Machines/MSX – Korean/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/Machines/MSX - Mitsubishi ML-F80/config.ini" -P "system/Machines/MSX - Mitsubishi ML-F80/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/Machines/MSX - Mitsubishi ML-FX1/config.ini" -P "system/Machines/MSX - Mitsubishi ML-FX1/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/Machines/MSX - National CF-1200/config.ini" -P "system/Machines/MSX - National CF-1200/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/Machines/MSX - National CF-2000/config.ini" -P "system/Machines/MSX - National CF-2000/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/Machines/MSX - National CF-2700/config.ini" -P "system/Machines/MSX - National CF-2700/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/Machines/MSX - National CF-3000/config.ini" -P "system/Machines/MSX - National CF-3000/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/Machines/MSX - National CF-3300/config.ini" -P "system/Machines/MSX - National CF-3300/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/Machines/MSX - National FS-1300/config.ini" -P "system/Machines/MSX - National FS-1300/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/Machines/MSX - National FS-4000/config.ini" -P "system/Machines/MSX - National FS-4000/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/Machines/MSX - Olympia PHC-2/config.ini" -P "system/Machines/MSX - Olympia PHC-2/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/Machines/MSX - Olympia PHC-28/config.ini" -P "system/Machines/MSX - Olympia PHC-28/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/Machines/MSX - Panasonic CF-2700G/config.ini" -P "system/Machines/MSX - Panasonic CF-2700G/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/Machines/MSX - Philips NMS-801/config.ini" -P "system/Machines/MSX - Philips NMS-801/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/Machines/MSX - Philips VG-8000/config.ini" -P "system/Machines/MSX - Philips VG-8000/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/Machines/MSX - Philips VG-8010/config.ini" -P "system/Machines/MSX - Philips VG-8010/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/Machines/MSX - Philips VG-8010F/config.ini" -P "system/Machines/MSX - Philips VG-8010F/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/Machines/MSX - Philips VG-8020-00/config.ini" -P "system/Machines/MSX - Philips VG-8020-00/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/Machines/MSX - Philips VG-8020-20/config.ini" -P "system/Machines/MSX - Philips VG-8020-20/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/Machines/MSX - Philips VG-8020F/config.ini" -P "system/Machines/MSX - Philips VG-8020F/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/Machines/MSX - Pioneer PX-7/config.ini" -P "system/Machines/MSX - Pioneer PX-7/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/Machines/MSX - Pioneer PX-V60/config.ini" -P "system/Machines/MSX - Pioneer PX-V60/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/Machines/MSX – Russian/config.ini" -P "system/Machines/MSX – Russian/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/Machines/MSX - Sanyo MPC-100/config.ini" -P "system/Machines/MSX - Sanyo MPC-100/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/Machines/MSX - Sanyo MPC-64/config.ini" -P "system/Machines/MSX - Sanyo MPC-64/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/Machines/MSX - Sanyo PHC-28L/config.ini" -P "system/Machines/MSX - Sanyo PHC-28L/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/Machines/MSX - Sanyo PHC-28S/config.ini" -P "system/Machines/MSX - Sanyo PHC-28S/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/Machines/MSX - Sanyo Wavy MPC-10/config.ini" -P "system/Machines/MSX - Sanyo Wavy MPC-10/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/Machines/MSX - Sharp Epcom HotBit 1.1/config.ini" -P "system/Machines/MSX - Sharp Epcom HotBit 1.1/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/Machines/MSX - Sharp Epcom HotBit 1.2/config.ini" -P "system/Machines/MSX - Sharp Epcom HotBit 1.2/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/Machines/MSX - Sharp Epcom HotBit 1.3b/config.ini" -P "system/Machines/MSX - Sharp Epcom HotBit 1.3b/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/Machines/MSX - Sharp Epcom HotBit 1.3p/config.ini" -P "system/Machines/MSX - Sharp Epcom HotBit 1.3p/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/Machines/MSX - Sony HB-10P/config.ini" -P "system/Machines/MSX - Sony HB-10P/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/Machines/MSX - Sony HB-201/config.ini" -P "system/Machines/MSX - Sony HB-201/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/Machines/MSX - Sony HB-201P/config.ini" -P "system/Machines/MSX - Sony HB-201P/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/Machines/MSX - Sony HB-20P/config.ini" -P "system/Machines/MSX - Sony HB-20P/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/Machines/MSX - Sony HB-501P/config.ini" -P "system/Machines/MSX - Sony HB-501P/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/Machines/MSX - Sony HB-55D/config.ini" -P "system/Machines/MSX - Sony HB-55D/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/Machines/MSX - Sony HB-55P/config.ini" -P "system/Machines/MSX - Sony HB-55P/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/Machines/MSX - Sony HB-75D/config.ini" -P "system/Machines/MSX - Sony HB-75D/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/Machines/MSX - Sony HB-75P/config.ini" -P "system/Machines/MSX - Sony HB-75P/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/Machines/MSX – Spanish/config.ini" -P "system/Machines/MSX – Spanish/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/Machines/MSX - Spectravideo SVI-728/config.ini" -P "system/Machines/MSX - Spectravideo SVI-728/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/Machines/MSX - Spectravideo SVI-738/config.ini" -P "system/Machines/MSX - Spectravideo SVI-738/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/Machines/MSX - Spectravideo SVI-738 Henrik Gilvad/config.ini" -P "system/Machines/MSX - Spectravideo SVI-738 Henrik Gilvad/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/Machines/MSX - Spectravideo SVI-738 Swedish/config.ini" -P "system/Machines/MSX - Spectravideo SVI-738 Swedish/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/Machines/MSX – Swedish/config.ini" -P "system/Machines/MSX – Swedish/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/Machines/MSX - Talent DPC-200/config.ini" -P "system/Machines/MSX - Talent DPC-200/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/Machines/MSX - Talent DPC-200A/config.ini" -P "system/Machines/MSX - Talent DPC-200A/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/Machines/MSX - Toshiba HX-10/config.ini" -P "system/Machines/MSX - Toshiba HX-10/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/Machines/MSX - Toshiba HX-10S/config.ini" -P "system/Machines/MSX - Toshiba HX-10S/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/Machines/MSX - Toshiba HX-20/config.ini" -P "system/Machines/MSX - Toshiba HX-20/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/Machines/MSXturboR/config.ini" -P "system/Machines/MSXturboR/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/Machines/MSXturboR – European/config.ini" -P "system/Machines/MSXturboR – European/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/Machines/MSXturboR - Panasonic FS-A1GT/config.ini" -P "system/Machines/MSXturboR - Panasonic FS-A1GT/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/Machines/MSXturboR - Panasonic FS-A1ST/config.ini" -P "system/Machines/MSXturboR - Panasonic FS-A1ST/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/Machines/MSXturboR - Panasonic FS-A1ST (a)/config.ini" -P "system/Machines/MSXturboR - Panasonic FS-A1ST (a)/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/Machines/MSXturboR - Panasonic FS-A1ST (b)/config.ini" -P "system/Machines/MSXturboR - Panasonic FS-A1ST (b)/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/Machines/MSX - Yamaha CX5M-1/config.ini" -P "system/Machines/MSX - Yamaha CX5M-1/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/Machines/MSX - Yamaha CX5M-128/config.ini" -P "system/Machines/MSX - Yamaha CX5M-128/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/Machines/MSX - Yamaha CX5M-2/config.ini" -P "system/Machines/MSX - Yamaha CX5M-2/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/Machines/MSX - Yamaha CX5MII/config.ini" -P "system/Machines/MSX - Yamaha CX5MII/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/Machines/MSX - Yamaha YIS303/config.ini" -P "system/Machines/MSX - Yamaha YIS303/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/Machines/MSX - Yamaha YIS503/config.ini" -P "system/Machines/MSX - Yamaha YIS503/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/Machines/MSX - Yamaha YIS503F/config.ini" -P "system/Machines/MSX - Yamaha YIS503F/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/Machines/MSX - Yamaha YIS503II/config.ini" -P "system/Machines/MSX - Yamaha YIS503II/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/Machines/MSX - Yamaha YIS503IIR/config.ini" -P "system/Machines/MSX - Yamaha YIS503IIR/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/Machines/MSX - Yamaha YIS503IIR Estonian/config.ini" -P "system/Machines/MSX - Yamaha YIS503IIR Estonian/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/Machines/MSX - Yamaha YIS503M/config.ini" -P "system/Machines/MSX - Yamaha YIS503M/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/Machines/MSX - Yashica YC-64/config.ini" -P "system/Machines/MSX - Yashica YC-64/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/Machines/MSX - Yeno DPC-64/config.ini" -P "system/Machines/MSX - Yeno DPC-64/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/Machines/MSX - Yeno MX64/config.ini" -P "system/Machines/MSX - Yeno MX64/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/Machines/SEGA – SC-3000/config.ini" -P "system/Machines/SEGA – SC-3000/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/Machines/SEGA – SF-7000/config.ini" -P "system/Machines/SEGA – SF-7000/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/Machines/SEGA – SF-7000/sf7000.rom" -P "system/Machines/SEGA – SF-7000/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/Machines/SEGA – SG-1000/config.ini" -P "system/Machines/SEGA – SG-1000/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/Machines/Shared Roms/ARAB1.ROM" -P "system/Machines/Shared Roms/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/Machines/Shared Roms/ARABIC.rom" -P "system/Machines/Shared Roms/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/Machines/Shared Roms/BEERIDE.ROM" -P "system/Machines/Shared Roms/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/Machines/Shared Roms/FMPAC.rom" -P "system/Machines/Shared Roms/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/Machines/Shared Roms/GCVMX80.ROM" -P "system/Machines/Shared Roms/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/Machines/Shared Roms/HANGUL.rom" -P "system/Machines/Shared Roms/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/Machines/Shared Roms/KANJI.rom" -P "system/Machines/Shared Roms/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/Machines/Shared Roms/MICROSOLDISK.ROM" -P "system/Machines/Shared Roms/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/Machines/Shared Roms/MOONSOUND.rom" -P "system/Machines/Shared Roms/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/Machines/Shared Roms/MSX2AREXT.ROM" -P "system/Machines/Shared Roms/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/Machines/Shared Roms/MSX2AR.ROM" -P "system/Machines/Shared Roms/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/Machines/Shared Roms/MSX2BREXT.rom" -P "system/Machines/Shared Roms/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/Machines/Shared Roms/MSX2BR.rom" -P "system/Machines/Shared Roms/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/Machines/Shared Roms/MSX2EXT.rom" -P "system/Machines/Shared Roms/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/Machines/Shared Roms/MSX2FREXT.rom" -P "system/Machines/Shared Roms/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/Machines/Shared Roms/MSX2FR.rom" -P "system/Machines/Shared Roms/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/Machines/Shared Roms/MSX2GEXT.rom" -P "system/Machines/Shared Roms/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/Machines/Shared Roms/MSX2G.rom" -P "system/Machines/Shared Roms/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/Machines/Shared Roms/MSX2HAN.rom" -P "system/Machines/Shared Roms/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/Machines/Shared Roms/MSX2JEXT.rom" -P "system/Machines/Shared Roms/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/Machines/Shared Roms/MSX2J.rom" -P "system/Machines/Shared Roms/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/Machines/Shared Roms/MSX2KREXT.rom" -P "system/Machines/Shared Roms/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/Machines/Shared Roms/MSX2KR.rom" -P "system/Machines/Shared Roms/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/Machines/Shared Roms/MSX2PEXT.rom" -P "system/Machines/Shared Roms/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/Machines/Shared Roms/MSX2PMUS.rom" -P "system/Machines/Shared Roms/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/Machines/Shared Roms/MSX2P.rom" -P "system/Machines/Shared Roms/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/Machines/Shared Roms/MSX2R2.ROM" -P "system/Machines/Shared Roms/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/Machines/Shared Roms/MSX2REXT.rom" -P "system/Machines/Shared Roms/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/Machines/Shared Roms/MSX2.rom" -P "system/Machines/Shared Roms/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/Machines/Shared Roms/MSX2R.rom" -P "system/Machines/Shared Roms/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/Machines/Shared Roms/MSX2SE.rom" -P "system/Machines/Shared Roms/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/Machines/Shared Roms/MSX2SPEXT.rom" -P "system/Machines/Shared Roms/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/Machines/Shared Roms/MSX2SP.rom" -P "system/Machines/Shared Roms/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/Machines/Shared Roms/MSXAR.ROM" -P "system/Machines/Shared Roms/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/Machines/Shared Roms/MSXBR.rom" -P "system/Machines/Shared Roms/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/Machines/Shared Roms/MSXDOS23.ROM" -P "system/Machines/Shared Roms/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/Machines/Shared Roms/MSXFR.rom" -P "system/Machines/Shared Roms/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/Machines/Shared Roms/MSXG.rom" -P "system/Machines/Shared Roms/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/Machines/Shared Roms/MSXHAN.rom" -P "system/Machines/Shared Roms/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/Machines/Shared Roms/MSXJ.rom" -P "system/Machines/Shared Roms/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/Machines/Shared Roms/MSXKANJI.rom" -P "system/Machines/Shared Roms/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/Machines/Shared Roms/MSXKR.rom" -P "system/Machines/Shared Roms/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/Machines/Shared Roms/MSXR2.ROM" -P "system/Machines/Shared Roms/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/Machines/Shared Roms/MSX.rom" -P "system/Machines/Shared Roms/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/Machines/Shared Roms/MSXR.rom" -P "system/Machines/Shared Roms/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/Machines/Shared Roms/MSXSE.ROM" -P "system/Machines/Shared Roms/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/Machines/Shared Roms/MSXSP.rom" -P "system/Machines/Shared Roms/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/Machines/Shared Roms/MSXTREXT.ROM" -P "system/Machines/Shared Roms/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/Machines/Shared Roms/MSXTRMUS.ROM" -P "system/Machines/Shared Roms/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/Machines/Shared Roms/MSXTROPT.ROM" -P "system/Machines/Shared Roms/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/Machines/Shared Roms/MSXTR.ROM" -P "system/Machines/Shared Roms/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/Machines/Shared Roms/NATIONALDISK.rom" -P "system/Machines/Shared Roms/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/Machines/Shared Roms/NOVAXIS.rom" -P "system/Machines/Shared Roms/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/Machines/Shared Roms/nowindDos1.rom" -P "system/Machines/Shared Roms/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/Machines/Shared Roms/nowindDos2.rom" -P "system/Machines/Shared Roms/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/Machines/Shared Roms/PAINT.rom" -P "system/Machines/Shared Roms/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/Machines/Shared Roms/PANASONICDISK.rom" -P "system/Machines/Shared Roms/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/Machines/Shared Roms/PHILIPSDISK.rom" -P "system/Machines/Shared Roms/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/Machines/Shared Roms/RS232.ROM" -P "system/Machines/Shared Roms/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/Machines/Shared Roms/Shared.txt" -P "system/Machines/Shared Roms/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/Machines/Shared Roms/SUNRISEIDE.rom" -P "system/Machines/Shared Roms/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/Machines/Shared Roms/SWP.rom" -P "system/Machines/Shared Roms/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/Machines/Shared Roms/XBASIC2.rom" -P "system/Machines/Shared Roms/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/Machines/SVI - Spectravideo SVI-318/config.ini" -P "system/Machines/SVI - Spectravideo SVI-318/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/Machines/SVI - Spectravideo SVI-318/svi318.rom" -P "system/Machines/SVI - Spectravideo SVI-318/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/Machines/SVI - Spectravideo SVI-328/config.ini" -P "system/Machines/SVI - Spectravideo SVI-328/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/Machines/SVI - Spectravideo SVI-328/svi328.rom" -P "system/Machines/SVI - Spectravideo SVI-328/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/Machines/SVI - Spectravideo SVI-328 80 Column/config.ini" -P "system/Machines/SVI - Spectravideo SVI-328 80 Column/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/Machines/SVI - Spectravideo SVI-328 80 Column/svi328a.rom" -P "system/Machines/SVI - Spectravideo SVI-328 80 Column/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/Machines/SVI - Spectravideo SVI-328 80 Column/svi806.rom" -P "system/Machines/SVI - Spectravideo SVI-328 80 Column/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/Machines/SVI - Spectravideo SVI-328 80 Swedish/config.ini" -P "system/Machines/SVI - Spectravideo SVI-328 80 Swedish/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/Machines/SVI - Spectravideo SVI-328 80 Swedish/svi328a.rom" -P "system/Machines/SVI - Spectravideo SVI-328 80 Swedish/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/Machines/SVI - Spectravideo SVI-328 80 Swedish/svi806se.rom" -P "system/Machines/SVI - Spectravideo SVI-328 80 Swedish/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/Machines/SVI - Spectravideo SVI-328 MK2/config.ini" -P "system/Machines/SVI - Spectravideo SVI-328 MK2/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/Machines/SVI - Spectravideo SVI-328 MK2/svi328a.rom" -P "system/Machines/SVI - Spectravideo SVI-328 MK2/"
wget -c "https://github.com/Luciano2018/LudOS-Bios/blob/main/Machines/SVI - Spectravideo SVI-328 MK2/svi806.rom" -P "system/Machines/SVI - Spectravideo SVI-328 MK2/"
echo
echo "Finish, now rebooting"
echo
reboot
echo
exit 0
