#!/bin/bash
echo "Removing all Bios, if are present"
###########################################################################
# Repositorio: LudOS-Bios 2024
# Por: Raspberry Pi Buenos Aires ("https://sites.google.com/view/raspberrypibuenosaires/)
# License: http://creativecommons.org/licenses/by-sa/4.0/
###########################################################################
RUTA=https://github.com/PIBSAS/LudOS-Bios/blob/main/
RUTA_ARCH="https://archive.org/download/bios_batocera/BatoceraV39Bios/bios/"
echo
rm "system/5200.rom"
rm "system/7800 BIOS (U).rom"
rm "system/areplay.bin"
rm "system/ATARIBAS.ROM"
rm "system/ATARIOSA.ROM"
rm "system/ATARIOSB.ROM"
rm "system/ATARIXL.ROM"
rm "system/bios7.bin"
rm "system/bios9.bin"
rm "system/bios_CD_E.bin"
rm "system/bios_CD_J.bin"
rm "system/bios_CD_U.bin"
rm "system/bios_E.sms"
rm "system/bios.gg"
rm "system/bios_J.sms"
rm "system/bios_MD.bin"
rm "system/bios.min"
rm "system/bios_U.sms"
rm "system/BS-X.bin"
rm "system/c52.bin"
rm "system/disksys.rom"
rm "system/dsi_bios7.bin"
rm "system/dsi_bios9.bin"
rm "system/dsi_firmware.bin"
rm "system/dsi_nand.bin"
rm "system/dsi_sd_card.bin"
rm "system/firmware.bin"
rm "system/g7400.bin"
rm "system/gamegenie.nes"
rm "system/gba_bios.bin"
rm "system/gb_bios.bin"
rm "system/gbc_bios.bin"
rm "system/gexpress.pce"
rm "system/ggenie.bin"
rm "system/jopac.bin"
rm "system/lynxboot.img"
rm "system/mpr-17933.bin"
rm "system/mpr-18811-mx.ic1"
rm "system/mpr-19367-mx.ic1"
rm "system/o2rom.bin"
rm "system/pcfx.rom"
rm "system/PSXONPSP660.bin"
rm "system/scph1001.bin"
rm "system/scph101.bin"
rm "system/scph5500.bin"
rm "system/scph5501.bin"
rm "system/scph5502.bin"
rm "system/scph7001.bin"
rm "system/sega_101.bin"
rm "system/sgb_bios.bin"
rm "system/sk2chip.bin"
rm "system/sk.bin"
rm "system/STBIOS.bin"
rm "system/syscard1.pce"
rm "system/syscard2.pce"
rm "system/syscard3.pce"
rm "system/np2kai/2608_BD.WAV"
rm "system/np2kai/2608_HH.WAV"
rm "system/np2kai/2608_RIM.WAV"
rm "system/np2kai/2608_SD.WAV"
rm "system/np2kai/2608_TOM.WAV"
rm "system/np2kai/2608_TOP.WAV"
rm "system/np2kai/bios.rom"
rm "system/np2kai/bios9821.rom"
rm "system/np2kai/d8000.rom"
rm "system/np2kai/font.bmp"
rm "system/np2kai/FONT.ROM"
rm "system/np2kai/itf.rom"
rm "system/np2kai/sound.rom"
rm "system/Databases/colecodb.xml"
rm "system/Databases/msxcaswavdb.xml"
rm "system/Databases/msxromdb.xml"
rm "system/Databases/msxsysromdb.xml"
rm "system/Databases/segadb.xml"
rm "system/Databases/svidb.xml"
rm "system/Machines/COL - Bit Corporation Dina/config.ini"
rm "system/Machines/COL - Bit Corporation Dina/czz50-1.rom"
rm "system/Machines/COL - Bit Corporation Dina/czz50-2.rom"
rm "system/Machines/COL – ColecoVision/coleco.rom"
rm "system/Machines/COL – ColecoVision/config.ini"
rm "system/Machines/COL - ColecoVision with Opcode Memory Extension/coleco.rom"
rm "system/Machines/COL - ColecoVision with Opcode Memory Extension/config.ini"
rm "system/Machines/COL - Spectravideo SVI-603 Coleco/config.ini"
rm "system/Machines/COL - Spectravideo SVI-603 Coleco/SVI603.ROM"
rm "system/Machines/Forte II Games – Pesadelo/config.ini"
rm "system/Machines/Forte II Games – Pesadelo/pesadelo.rom"
rm "system/Machines/MSX/config.ini"
rm "system/Machines/MSX2/config.ini"
rm "system/Machines/MSX2+/config.ini"
rm "system/Machines/MSX2 - Al Alamiah AX-350/config.ini"
rm "system/Machines/MSX2 - Al Alamiah AX-370/config.ini"
rm "system/Machines/MSX2 – Arabic/config.ini"
rm "system/Machines/MSX2 – Brazilian/config.ini"
rm "system/Machines/MSX2+ - Brazilian/config.ini"
rm "system/Machines/MSX2 – C-BIOS/cbios_logo_msx2.rom"
rm "system/Machines/MSX2 – C-BIOS/cbios_main_msx2.rom"
rm "system/Machines/MSX2 – C-BIOS/cbios_sub.rom"
rm "system/Machines/MSX2 – C-BIOS/cbios.txt"
rm "system/Machines/MSX2 – C-BIOS/config.ini"
rm "system/Machines/MSX2+ - C-BIOS/cbios_logo_msx2+.rom"
rm "system/Machines/MSX2+ - C-BIOS/cbios_main_msx2+.rom"
rm "system/Machines/MSX2+ - C-BIOS/cbios_music.rom"
rm "system/Machines/MSX2+ - C-BIOS/cbios_sub.rom"
rm "system/Machines/MSX2+ - C-BIOS/cbios.txt"
rm "system/Machines/MSX2+ - C-BIOS/config.ini"
rm "system/Machines/MSX2+ - Ciel Expert 3 IDE/config.ini"
rm "system/Machines/MSX2+ - Ciel Expert 3 Turbo/config.ini"
rm "system/Machines/MSX2 - Daewoo CPC-300/config.ini"
rm "system/Machines/MSX2 - Daewoo CPC-300E/config.ini"
rm "system/Machines/MSX2 - Daewoo CPC-400/config.ini"
rm "system/Machines/MSX2 - Daewoo CPC-400S/config.ini"
rm "system/Machines/MSX2 – Estonian/config.ini"
rm "system/Machines/MSX2+ - European/config.ini"
rm "system/Machines/MSX2+ - European/KANJI.rom"
rm "system/Machines/MSX2+ - European/Msx2pe.rom"
rm "system/Machines/MSX2+ - European/Msx2pexte.rom"
rm "system/Machines/MSX2+ - European/MSX2PMUS.rom"
rm "system/Machines/MSX2+ - European/MSXKANJI.rom"
rm "system/Machines/MSX2+ - European/PANASONICDISK.rom"
rm "system/Machines/MSX2+ - European/XBASIC2.rom"
rm "system/Machines/MSX2 – French/config.ini"
rm "system/Machines/MSX2 – German/config.ini"
rm "system/Machines/MSX2 - Gradiente Expert 2.0/config.ini"
rm "system/Machines/MSX2+ - Gradiente Expert AC88+/config.ini"
rm "system/Machines/MSX2+ - Gradiente Expert DDX+/config.ini"
rm "system/Machines/MSX2 – Japanese/config.ini"
rm "system/Machines/MSX2 – Korean/config.ini"
rm "system/Machines/MSX2+ - MSXPLAYer 2003/config.ini"
rm "system/Machines/MSX2 - National FS-4500/config.ini"
rm "system/Machines/MSX2 - National FS-4600/config.ini"
rm "system/Machines/MSX2 - National FS-4700/config.ini"
rm "system/Machines/MSX2 - National FS-5000/config.ini"
rm "system/Machines/MSX2 - National FS-5500F1/config.ini"
rm "system/Machines/MSX2 - National FS-5500F2/config.ini"
rm "system/Machines/MSX2 - Only PSG/config.ini"
rm "system/Machines/MSX2 - Panasonic FS-A1/config.ini"
rm "system/Machines/MSX2 - Panasonic FS-A1 (a)/config.ini"
rm "system/Machines/MSX2 - Panasonic FS-A1F/config.ini"
rm "system/Machines/MSX2 - Panasonic FS-A1FM/config.ini"
rm "system/Machines/MSX2+ - Panasonic FS-A1FX/config.ini"
rm "system/Machines/MSX2 - Panasonic FS-A1MK2/config.ini"
rm "system/Machines/MSX2+ - Panasonic FS-A1WSX/config.ini"
rm "system/Machines/MSX2+ - Panasonic FS-A1WX/config.ini"
rm "system/Machines/MSX2+ - Panasonic FS-A1WX (a)/config.ini"
rm "system/Machines/MSX2 - Philips NMS-8220/config.ini"
rm "system/Machines/MSX2 - Philips NMS-8220 (a)/config.ini"
rm "system/Machines/MSX2 - Philips NMS-8245/config.ini"
rm "system/Machines/MSX2 - Philips NMS-8245F/config.ini"
rm "system/Machines/MSX2 - Philips NMS-8250/config.ini"
rm "system/Machines/MSX2 - Philips NMS-8255/config.ini"
rm "system/Machines/MSX2 - Philips NMS-8280/config.ini"
rm "system/Machines/MSX2 - Philips NMS-8280G/config.ini"
rm "system/Machines/MSX2 - Philips VG-8230/config.ini"
rm "system/Machines/MSX2 - Philips VG-8235/config.ini"
rm "system/Machines/MSX2 - Philips VG-8235F/config.ini"
rm "system/Machines/MSX2 - Philips VG-8240/config.ini"
rm "system/Machines/MSX2 – Russian/config.ini"
rm "system/Machines/MSX2 - Sanyo Wavy MPC-25FD/config.ini"
rm "system/Machines/MSX2 - Sanyo Wavy PHC-23/config.ini"
rm "system/Machines/MSX2+ - Sanyo Wavy PHC-35J/config.ini"
rm "system/Machines/MSX2+ - Sanyo Wavy PHC-70FD1/config.ini"
rm "system/Machines/MSX2+ - Sanyo Wavy PHC-70FD2/config.ini"
rm "system/Machines/MSX2 - Sharp Epcom HotBit 2.0/config.ini"
rm "system/Machines/MSX2 - Sony HB-F1/config.ini"
rm "system/Machines/MSX2 - Sony HB-F1II/config.ini"
rm "system/Machines/MSX2 - Sony HB-F1XD/config.ini"
rm "system/Machines/MSX2+ - Sony HB-F1XDJ/config.ini"
rm "system/Machines/MSX2 - Sony HB-F1XDMK2/config.ini"
rm "system/Machines/MSX2+ - Sony HB-F1XV/config.ini"
rm "system/Machines/MSX2 - Sony HB-F500/config.ini"
rm "system/Machines/MSX2 - Sony HB-F500P/config.ini"
rm "system/Machines/MSX2 - Sony HB-F700D/config.ini"
rm "system/Machines/MSX2 - Sony HB-F700F/config.ini"
rm "system/Machines/MSX2 - Sony HB-F700P/config.ini"
rm "system/Machines/MSX2 - Sony HB-F700S/config.ini"
rm "system/Machines/MSX2 - Sony HB-F900/config.ini"
rm "system/Machines/MSX2 - Sony HB-F900 (a)/config.ini"
rm "system/Machines/MSX2 - Sony HB-F9P/config.ini"
rm "system/Machines/MSX2 - Sony HB-F9P Russian/config.ini"
rm "system/Machines/MSX2 - Sony HB-F9S/config.ini"
rm "system/Machines/MSX2+ - Sony HB-F9S+/config.ini"
rm "system/Machines/MSX2 - Sony HB-G900AP/config.ini"
rm "system/Machines/MSX2 - Sony HB-G900P/config.ini"
rm "system/Machines/MSX2 – Spanish/config.ini"
rm "system/Machines/MSX2 - Spectravideo SVI-738-2 CUC/config.ini"
rm "system/Machines/MSX2 - Spectravideo SVI-738-2 JP Grobler/config.ini"
rm "system/Machines/MSX2 - Spectravideo SVI-738-2 LC Grosso/config.ini"
rm "system/Machines/MSX2 – Swedish/config.ini"
rm "system/Machines/MSX2 - Talent TPC-310/config.ini"
rm "system/Machines/MSX2 - Toshiba HX-23/config.ini"
rm "system/Machines/MSX2 - Toshiba HX-23F/config.ini"
rm "system/Machines/MSX2 - Virtual Haesung Console/config.ini"
rm "system/Machines/MSX2 - Yamaha CX7M/config.ini"
rm "system/Machines/MSX2 - Yamaha CX7M-128/config.ini"
rm "system/Machines/MSX - Al Alamiah AX-170/config.ini"
rm "system/Machines/MSX – Arabic/config.ini"
rm "system/Machines/MSX – Brazilian/config.ini"
rm "system/Machines/MSX - Canon V-10/config.ini"
rm "system/Machines/MSX - Canon V-20/config.ini"
rm "system/Machines/MSX – C-BIOS/cbios_logo_msx1.rom"
rm "system/Machines/MSX – C-BIOS/cbios_main_msx1.rom"
rm "system/Machines/MSX – C-BIOS/cbios.txt"
rm "system/Machines/MSX – C-BIOS/config.ini"
rm "system/Machines/MSX - Daewoo DPC-100/config.ini"
rm "system/Machines/MSX - Daewoo DPC-180/config.ini"
rm "system/Machines/MSX - Daewoo DPC-200/config.ini"
rm "system/Machines/MSX - Daewoo DPC-200E/config.ini"
rm "system/Machines/MSX – Estonian/config.ini"
rm "system/Machines/MSX - Frael Bruc 100-1/config.ini"
rm "system/Machines/MSX – French/config.ini"
rm "system/Machines/MSX – German/config.ini"
rm "system/Machines/MSX - Goldstar FC-200/config.ini"
rm "system/Machines/MSX - Gradiente Expert 1.0/config.ini"
rm "system/Machines/MSX - Gradiente Expert 1.1/config.ini"
rm "system/Machines/MSX - Gradiente Expert 1.3/config.ini"
rm "system/Machines/MSX - Gradiente Expert DDPlus/config.ini"
rm "system/Machines/MSX - Gradiente Expert Plus/config.ini"
rm "system/Machines/MSX – Japanese/config.ini"
rm "system/Machines/MSX - JVC HC-7GB/config.ini"
rm "system/Machines/MSX – Korean/config.ini"
rm "system/Machines/MSX - Mitsubishi ML-F80/config.ini"
rm "system/Machines/MSX - Mitsubishi ML-FX1/config.ini"
rm "system/Machines/MSX - National CF-1200/config.ini"
rm "system/Machines/MSX - National CF-2000/config.ini"
rm "system/Machines/MSX - National CF-2700/config.ini"
rm "system/Machines/MSX - National CF-3000/config.ini"
rm "system/Machines/MSX - National CF-3300/config.ini"
rm "system/Machines/MSX - National FS-1300/config.ini"
rm "system/Machines/MSX - National FS-4000/config.ini"
rm "system/Machines/MSX - Olympia PHC-2/config.ini"
rm "system/Machines/MSX - Olympia PHC-28/config.ini"
rm "system/Machines/MSX - Panasonic CF-2700G/config.ini"
rm "system/Machines/MSX - Philips NMS-801/config.ini"
rm "system/Machines/MSX - Philips VG-8000/config.ini"
rm "system/Machines/MSX - Philips VG-8010/config.ini"
rm "system/Machines/MSX - Philips VG-8010F/config.ini"
rm "system/Machines/MSX - Philips VG-8020-00/config.ini"
rm "system/Machines/MSX - Philips VG-8020-20/config.ini"
rm "system/Machines/MSX - Philips VG-8020F/config.ini"
rm "system/Machines/MSX - Pioneer PX-7/config.ini"
rm "system/Machines/MSX - Pioneer PX-V60/config.ini"
rm "system/Machines/MSX – Russian/config.ini"
rm "system/Machines/MSX - Sanyo MPC-100/config.ini"
rm "system/Machines/MSX - Sanyo MPC-64/config.ini"
rm "system/Machines/MSX - Sanyo PHC-28L/config.ini"
rm "system/Machines/MSX - Sanyo PHC-28S/config.ini"
rm "system/Machines/MSX - Sanyo Wavy MPC-10/config.ini"
rm "system/Machines/MSX - Sharp Epcom HotBit 1.1/config.ini"
rm "system/Machines/MSX - Sharp Epcom HotBit 1.2/config.ini"
rm "system/Machines/MSX - Sharp Epcom HotBit 1.3b/config.ini"
rm "system/Machines/MSX - Sharp Epcom HotBit 1.3p/config.ini"
rm "system/Machines/MSX - Sony HB-10P/config.ini"
rm "system/Machines/MSX - Sony HB-201/config.ini"
rm "system/Machines/MSX - Sony HB-201P/config.ini"
rm "system/Machines/MSX - Sony HB-20P/config.ini"
rm "system/Machines/MSX - Sony HB-501P/config.ini"
rm "system/Machines/MSX - Sony HB-55D/config.ini"
rm "system/Machines/MSX - Sony HB-55P/config.ini"
rm "system/Machines/MSX - Sony HB-75D/config.ini"
rm "system/Machines/MSX - Sony HB-75P/config.ini"
rm "system/Machines/MSX – Spanish/config.ini"
rm "system/Machines/MSX - Spectravideo SVI-728/config.ini"
rm "system/Machines/MSX - Spectravideo SVI-738/config.ini"
rm "system/Machines/MSX - Spectravideo SVI-738 Henrik Gilvad/config.ini"
rm "system/Machines/MSX - Spectravideo SVI-738 Swedish/config.ini"
rm "system/Machines/MSX – Swedish/config.ini"
rm "system/Machines/MSX - Talent DPC-200/config.ini"
rm "system/Machines/MSX - Talent DPC-200A/config.ini"
rm "system/Machines/MSX - Toshiba HX-10/config.ini"
rm "system/Machines/MSX - Toshiba HX-10S/config.ini"
rm "system/Machines/MSX - Toshiba HX-20/config.ini"
rm "system/Machines/MSXturboR/config.ini"
rm "system/Machines/MSXturboR – European/config.ini"
rm "system/Machines/MSXturboR - Panasonic FS-A1GT/config.ini"
rm "system/Machines/MSXturboR - Panasonic FS-A1ST/config.ini"
rm "system/Machines/MSXturboR - Panasonic FS-A1ST (a)/config.ini"
rm "system/Machines/MSXturboR - Panasonic FS-A1ST (b)/config.ini"
rm "system/Machines/MSX - Yamaha CX5M-1/config.ini"
rm "system/Machines/MSX - Yamaha CX5M-128/config.ini"
rm "system/Machines/MSX - Yamaha CX5M-2/config.ini"
rm "system/Machines/MSX - Yamaha CX5MII/config.ini"
rm "system/Machines/MSX - Yamaha YIS303/config.ini"
rm "system/Machines/MSX - Yamaha YIS503/config.ini"
rm "system/Machines/MSX - Yamaha YIS503F/config.ini"
rm "system/Machines/MSX - Yamaha YIS503II/config.ini"
rm "system/Machines/MSX - Yamaha YIS503IIR/config.ini"
rm "system/Machines/MSX - Yamaha YIS503IIR Estonian/config.ini"
rm "system/Machines/MSX - Yamaha YIS503M/config.ini"
rm "system/Machines/MSX - Yashica YC-64/config.ini"
rm "system/Machines/MSX - Yeno DPC-64/config.ini"
rm "system/Machines/MSX - Yeno MX64/config.ini"
rm "system/Machines/SEGA – SC-3000/config.ini"
rm "system/Machines/SEGA – SF-7000/config.ini"
rm "system/Machines/SEGA – SF-7000/sf7000.rom"
rm "system/Machines/SEGA – SG-1000/config.ini"
rm "system/Machines/Shared Roms/ARAB1.ROM"
rm "system/Machines/Shared Roms/ARABIC.rom"
rm "system/Machines/Shared Roms/BEERIDE.ROM"
rm "system/Machines/Shared Roms/FMPAC.rom"
rm "system/Machines/Shared Roms/GCVMX80.ROM"
rm "system/Machines/Shared Roms/HANGUL.rom"
rm "system/Machines/Shared Roms/KANJI.rom"
rm "system/Machines/Shared Roms/MICROSOLDISK.ROM"
rm "system/Machines/Shared Roms/MOONSOUND.rom"
rm "system/Machines/Shared Roms/MSX2AREXT.ROM"
rm "system/Machines/Shared Roms/MSX2AR.ROM"
rm "system/Machines/Shared Roms/MSX2BREXT.rom"
rm "system/Machines/Shared Roms/MSX2BR.rom"
rm "system/Machines/Shared Roms/MSX2EXT.rom"
rm "system/Machines/Shared Roms/MSX2FREXT.rom"
rm "system/Machines/Shared Roms/MSX2FR.rom"
rm "system/Machines/Shared Roms/MSX2GEXT.rom"
rm "system/Machines/Shared Roms/MSX2G.rom"
rm "system/Machines/Shared Roms/MSX2HAN.rom"
rm "system/Machines/Shared Roms/MSX2JEXT.rom"
rm "system/Machines/Shared Roms/MSX2J.rom"
rm "system/Machines/Shared Roms/MSX2KREXT.rom"
rm "system/Machines/Shared Roms/MSX2KR.rom"
rm "system/Machines/Shared Roms/MSX2PEXT.rom"
rm "system/Machines/Shared Roms/MSX2PMUS.rom"
rm "system/Machines/Shared Roms/MSX2P.rom"
rm "system/Machines/Shared Roms/MSX2R2.ROM"
rm "system/Machines/Shared Roms/MSX2REXT.rom"
rm "system/Machines/Shared Roms/MSX2.rom"
rm "system/Machines/Shared Roms/MSX2R.rom"
rm "system/Machines/Shared Roms/MSX2SE.rom"
rm "system/Machines/Shared Roms/MSX2SPEXT.rom"
rm "system/Machines/Shared Roms/MSX2SP.rom"
rm "system/Machines/Shared Roms/MSXAR.ROM"
rm "system/Machines/Shared Roms/MSXBR.rom"
rm "system/Machines/Shared Roms/MSXDOS23.ROM"
rm "system/Machines/Shared Roms/MSXFR.rom"
rm "system/Machines/Shared Roms/MSXG.rom"
rm "system/Machines/Shared Roms/MSXHAN.rom"
rm "system/Machines/Shared Roms/MSXJ.rom"
rm "system/Machines/Shared Roms/MSXKANJI.rom"
rm "system/Machines/Shared Roms/MSXKR.rom"
rm "system/Machines/Shared Roms/MSXR2.ROM"
rm "system/Machines/Shared Roms/MSX.rom"
rm "system/Machines/Shared Roms/MSXR.rom"
rm "system/Machines/Shared Roms/MSXSE.ROM"
rm "system/Machines/Shared Roms/MSXSP.rom"
rm "system/Machines/Shared Roms/MSXTREXT.ROM"
rm "system/Machines/Shared Roms/MSXTRMUS.ROM"
rm "system/Machines/Shared Roms/MSXTROPT.ROM"
rm "system/Machines/Shared Roms/MSXTR.ROM"
rm "system/Machines/Shared Roms/NATIONALDISK.rom"
rm "system/Machines/Shared Roms/NOVAXIS.rom"
rm "system/Machines/Shared Roms/nowindDos1.rom"
rm "system/Machines/Shared Roms/nowindDos2.rom"
rm "system/Machines/Shared Roms/PAINT.rom"
rm "system/Machines/Shared Roms/PANASONICDISK.rom"
rm "system/Machines/Shared Roms/PHILIPSDISK.rom"
rm "system/Machines/Shared Roms/RS232.ROM"
rm "system/Machines/Shared Roms/Shared.txt"
rm "system/Machines/Shared Roms/SUNRISEIDE.rom"
rm "system/Machines/Shared Roms/SWP.rom"
rm "system/Machines/Shared Roms/XBASIC2.rom"
rm "system/Machines/SVI - Spectravideo SVI-318/config.ini"
rm "system/Machines/SVI - Spectravideo SVI-318/svi318.rom"
rm "system/Machines/SVI - Spectravideo SVI-328/config.ini"
rm "system/Machines/SVI - Spectravideo SVI-328/svi328.rom"
rm "system/Machines/SVI - Spectravideo SVI-328 80 Column/config.ini"
rm "system/Machines/SVI - Spectravideo SVI-328 80 Column/svi328a.rom"
rm "system/Machines/SVI - Spectravideo SVI-328 80 Column/svi806.rom"
rm "system/Machines/SVI - Spectravideo SVI-328 80 Swedish/config.ini"
rm "system/Machines/SVI - Spectravideo SVI-328 80 Swedish/svi328a.rom"
rm "system/Machines/SVI - Spectravideo SVI-328 80 Swedish/svi806se.rom"
rm "system/Machines/SVI - Spectravideo SVI-328 MK2/config.ini"
rm "system/Machines/SVI - Spectravideo SVI-328 MK2/svi328a.rom"
rm "system/Machines/SVI - Spectravideo SVI-328 MK2/svi806.rom"
echo
echo "Making folders to put bios"
echo
mkdir "system/np2kai/"
mkdir "system/Databases/"
echo
echo "Getting Bios"
echo
wget -c "${RUTA}5200.rom" -P "system/"
wget -c "${RUTA}7800 BIOS (U).rom" -P "system/"
wget -c "${RUTA}areplay.bin" -P "system/"
wget -c "${RUTA}ATARIBAS.ROM" -P "system/"
wget -c "${RUTA}ATARIOSA.ROM" -P "system/"
wget -c "${RUTA}ATARIOSB.ROM" -P "system/"
wget -c "${RUTA}ATARIXL.ROM" -P "system/"
wget -c "${RUTA}bios7.bin" -P "system/"
wget -c "${RUTA}bios9.bin" -P "system/"
wget -c "${RUTA}bios_CD_E.bin" -P "system/"
wget -c "${RUTA}bios_CD_J.bin" -P "system/"
wget -c "${RUTA}bios_CD_U.bin" -P "system/"
wget -c "${RUTA}bios_E.sms" -P "system/"
wget -c "${RUTA}bios.gg" -P "system/"
wget -c "${RUTA}bios_J.sms" -P "system/"
wget -c "${RUTA}bios_MD.bin" -P "system/"
wget -c "${RUTA}bios.min" -P "system/"
wget -c "${RUTA}bios_U.sms" -P "system/"
wget -c "${RUTA}BS-X.bin" -P "system/"
wget -c "${RUTA}c52.bin" -P "system/"
wget -c "${RUTA}disksys.rom" -P "system/"
wget -c "${RUTA}dsi_bios7.bin" -P "system/"
wget -c "${RUTA}dsi_bios9.bin" -P "system/"
wget -c "${RUTA}dsi_firmware.bin" -P "system/"
wget -c "${RUTA_ARCH}dsi_nand.bin" -P "system/"
wget -c "${RUTA_ARCH}dsi_sd_card.bin" -P "system/"
wget -c "${RUTA}firmware.bin" -P "system/"
wget -c "${RUTA}g7400.bin" -P "system/"
wget -c "${RUTA}gamegenie.nes" -P "system/"
wget -c "${RUTA}gba_bios.bin" -P "system/"
wget -c "${RUTA}gb_bios.bin" -P "system/"
wget -c "${RUTA}gbc_bios.bin" -P "system/"
wget -c "${RUTA}gexpress.pce" -P "system/"
wget -c "${RUTA}ggenie.bin" -P "system/"
wget -c "${RUTA}jopac.bin" -P "system/"
wget -c "${RUTA}lynxboot.img" -P "system/"
wget -c "${RUTA}mpr-17933.bin" -P "system/"
wget -c "${RUTA}mpr-18811-mx.ic1" -P "system/"
wget -c "${RUTA}mpr-19367-mx.ic1" -P "system/"
wget -c "${RUTA}o2rom.bin" -P "system/"
wget -c "${RUTA}pcfx.rom" -P "system/"
wget -c "${RUTA}PSXONPSP660.bin" -P "system/"
wget -c "${RUTA}scph1001.bin" -P "system/"
wget -c "${RUTA}scph101.bin" -P "system/"
wget -c "${RUTA}scph5500.bin" -P "system/"
wget -c "${RUTA}scph5501.bin" -P "system/"
wget -c "${RUTA}scph5502.bin" -P "system/"
wget -c "${RUTA}scph7001.bin" -P "system/"
wget -c "${RUTA}sega_101.bin" -P "system/"
wget -c "${RUTA}sgb_bios.bin" -P "system/"
wget -c "${RUTA}sk2chip.bin" -P "system/"
wget -c "${RUTA}sk.bin" -P "system/"
wget -c "${RUTA}STBIOS.bin" -P "system/"
wget -c "${RUTA}syscard1.pce" -P "system/"
wget -c "${RUTA}syscard2.pce" -P "system/"
wget -c "${RUTA}syscard3.pce" -P "system/"
wget -c "${RUTA}np2kai/2608_BD.WAV" -P "system/np2kai/"
wget -c "${RUTA}np2kai/2608_HH.WAV" -P "system/np2kai/"
wget -c "${RUTA}np2kai/2608_RIM.WAV" -P "system/np2kai/"
wget -c "${RUTA}np2kai/2608_SD.WAV" -P "system/np2kai/"
wget -c "${RUTA}np2kai/2608_TOM.WAV" -P "system/np2kai/"
wget -c "${RUTA}np2kai/2608_TOP.WAV" -P "system/np2kai/"
wget -c "${RUTA}np2kai/bios.rom" -P "system/np2kai/"
wget -c "${RUTA}np2kai/bios9821.rom" -P "system/np2kai/"
wget -c "${RUTA}np2kai/d8000.rom" -P "system/np2kai/"
wget -c "${RUTA}np2kai/font.bmp" -P "system/np2kai/"
wget -c "${RUTA}np2kai/FONT.ROM" -P "system/np2kai/"
wget -c "${RUTA}np2kai/itf.rom" -P "system/np2kai/"
wget -c "${RUTA}np2kai/sound.rom" -P "system/np2kai/"
wget -c "${RUTA}Databases/colecodb.xml" -P "system/Databases/"
wget -c "${RUTA}Databases/msxcaswavdb.xml" -P "system/Databases/"
wget -c "${RUTA}Databases/msxromdb.xml" -P "system/Databases/"
wget -c "${RUTA}Databases/msxsysromdb.xml" -P "system/Databases/"
wget -c "${RUTA}Databases/segadb.xml" -P "system/Databases/"
wget -c "${RUTA}Databases/svidb.xml" -P "system/Databases/"
wget -c "https://github.com/PIBSAS/LudOS-Bios/raw/main/Machines.zip" -P "system/"
unzip system/Machines.zip -d system/
rm system/Machines.zip
rm LudOS_Bios_PC.sh
echo "Finish, now rebooting"
echo
reboot
echo
exit 0
